#!/usr/bin/env bash
#
# Rev 1.5 §13 — decide whether an installed Browser Stream Host is what it claims to be.
#
# This is the gate. `bootstrap.sh` completing proves files were written; it proves nothing
# about whether the debugger is fenced or the control agent refuses a stranger, and those
# are the two facts this host exists to guarantee.
#
# Every check reports GREEN, RED or UNKNOWN. UNKNOWN is not a pass: a check that could not
# run is recorded as one that did not run, because a qualification script that reports
# success for a check it skipped is worse than having no script.
set -uo pipefail

INSTANCE="${VAN_BROWSER_INSTANCE:-}"
PROFILE_MOUNT="${VAN_BROWSER_PROFILE_MOUNT:-/var/lib/van-browser-profiles}"

results=()
overall=0

record() { # name status detail
  results+=("{\"check\":\"$1\",\"status\":\"$2\",\"detail\":$(printf '%s' "$3" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')}")
  if [ "$2" != "GREEN" ]; then overall=1; fi
}

case "$INSTANCE" in
  public) offset=0 ;;
  owner) offset=1 ;;
  *)
    record "profile_instance_selected" "UNKNOWN" "set VAN_BROWSER_INSTANCE to public or owner; a shared singleton cannot qualify both profiles"
    printf '{"host":"%s","checked_at":"%s","checks":[%s]}\n' "$(hostname)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(IFS=,; echo "${results[*]}")"
    exit "$overall"
    ;;
esac
CDP_PORT="${VAN_BROWSER_CDP_PORT:-$((9222 + offset))}"
AGENT_PORT="${VAN_BROWSER_CONTROL_PORT:-$((9443 + offset))}"
STREAM_PORT="${VAN_BROWSER_STREAM_PORT:-$((8443 + offset))}"
PKI_DIR="${VAN_BROWSER_PKI_DIR:-/etc/van-browser-stream/profiles/$INSTANCE/control-pki}"
CHROMIUM_UNIT="van-browser-chromium@$INSTANCE.service"
CHROMIUM_USER="van-browser-$INSTANCE"
record "profile_instance_selected" "GREEN" "qualifying the $INSTANCE stack and its separate listener/Unix identities"
for role in chromium control-agent stream transfer-stage; do
  unit="van-browser-$role@$INSTANCE.service"
  if systemctl is-active --quiet "$unit" 2>/dev/null; then
    record "instance_${role}_active" "GREEN" "$unit is active"
  else
    record "instance_${role}_active" "UNKNOWN" "$unit is not observed active"
  fi
done

# ---------------------------------------------------------------- 1. RB-117
# The check that comes first because it is the one that turns this host into a remote shell.
non_loopback=$(ip -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1)
if [ -z "$non_loopback" ]; then
  record "cdp_not_public" "UNKNOWN" "no global addresses found; cannot prove the debugger is fenced"
else
  exposed=""
  for addr in $non_loopback; do
    if timeout 2 bash -c "</dev/tcp/$addr/$CDP_PORT" 2>/dev/null; then
      exposed="$exposed $addr"
    fi
  done
  if [ -n "$exposed" ]; then
    record "cdp_not_public" "RED" "the debugger answered on:$exposed"
  else
    record "cdp_not_public" "GREEN" "debugger did not answer on any global address ($non_loopback)"
  fi
fi

# The other half: it must actually be listening on loopback, or the first check passed
# because nothing is running.
if timeout 2 bash -c "</dev/tcp/127.0.0.1/$CDP_PORT" 2>/dev/null; then
  record "cdp_on_loopback" "GREEN" "debugger answers on 127.0.0.1:$CDP_PORT"
else
  record "cdp_on_loopback" "RED" "nothing is listening on 127.0.0.1:$CDP_PORT, so the fencing check above proves nothing"
fi

# ---------------------------------------------------------------- 2. mTLS admission and refusals
# Use the actual private bind. A listener refusal is meaningful only after a
# certificate from the admitted private CA successfully connects to that listener.
CONTROL_BIND="${VAN_BROWSER_CONTROL_BIND:-}"
QUALIFY_CERT="${VAN_BROWSER_QUALIFY_CLIENT_CERT:-$PKI_DIR/client-browser-harness.trading-core.van.internal.crt}"
QUALIFY_KEY="${VAN_BROWSER_QUALIFY_CLIENT_KEY:-$PKI_DIR/client-browser-harness.trading-core.van.internal.key}"
TLS_PROBE="$(dirname "${BASH_SOURCE[0]}")/qualify_tls.py"

probe_result() {
  python3 "$TLS_PROBE" --host "$CONTROL_BIND" --port "$AGENT_PORT" --ca "$PKI_DIR/ca.crt" "$@" |
    python3 -c 'import json,sys; print(json.load(sys.stdin)["result"])'
}
private_control_bind() {
  python3 - "$CONTROL_BIND" <<'PYBIND'
import ipaddress, sys
try:
    address = ipaddress.ip_address(sys.argv[1])
    valid = address.is_private and not address.is_loopback and not address.is_unspecified
except ValueError:
    valid = False
raise SystemExit(0 if valid else 2)
PYBIND
}

if ! private_control_bind; then
  record "agent_admits_known_client" "UNKNOWN" "VAN_BROWSER_CONTROL_BIND must name the actual private VCN listener"
  record "agent_refuses_anonymous" "UNKNOWN" "no verified admitted-client listener prerequisite"
  record "agent_refuses_foreign_ca" "UNKNOWN" "no verified admitted-client listener prerequisite"
elif [ ! -f "$QUALIFY_CERT" ] || [ ! -f "$QUALIFY_KEY" ]; then
  record "agent_admits_known_client" "UNKNOWN" "no supplied admitted-client certificate/key; credentials are not copied or generated by qualification"
  record "agent_refuses_anonymous" "UNKNOWN" "no verified admitted-client listener prerequisite"
  record "agent_refuses_foreign_ca" "UNKNOWN" "no verified admitted-client listener prerequisite"
else
  admitted=$(probe_result --cert "$QUALIFY_CERT" --key "$QUALIFY_KEY")
  if [ "$admitted" != "ADMITTED" ]; then
    record "agent_admits_known_client" "RED" "the known client did not complete verified TLS on the private listener ($admitted)"
    record "agent_refuses_anonymous" "UNKNOWN" "no verified admitted-client listener prerequisite"
    record "agent_refuses_foreign_ca" "UNKNOWN" "no verified admitted-client listener prerequisite"
  else
    record "agent_admits_known_client" "GREEN" "known client completed verified TLS on the actual private listener"
    anonymous=$(probe_result)
    if [ "$anonymous" = "DENIED" ]; then
      record "agent_refuses_anonymous" "GREEN" "verified server sent an explicit certificate-denial TLS alert"
    elif [ "$anonymous" = "ADMITTED" ]; then
      record "agent_refuses_anonymous" "RED" "anonymous TLS was admitted"
    else
      record "agent_refuses_anonymous" "UNKNOWN" "network/TLS failure or no explicit certificate denial ($anonymous)"
    fi
    if [ -f "$PKI_DIR/foreign-client.crt" ] && [ -f "$PKI_DIR/foreign-client.key" ]; then
      foreign=$(probe_result --cert "$PKI_DIR/foreign-client.crt" --key "$PKI_DIR/foreign-client.key")
      if [ "$foreign" = "DENIED" ]; then
        record "agent_refuses_foreign_ca" "GREEN" "verified server sent an explicit certificate-denial TLS alert"
      elif [ "$foreign" = "ADMITTED" ]; then
        record "agent_refuses_foreign_ca" "RED" "a foreign certificate was admitted"
      else
        record "agent_refuses_foreign_ca" "UNKNOWN" "network/TLS failure or no explicit certificate denial ($foreign)"
      fi
    else
      record "agent_refuses_foreign_ca" "UNKNOWN" "no supplied foreign certificate/key; run make-stream-pki.sh --with-foreign-test-cert"
    fi
  fi
fi

# ---------------------------------------------------------------- 3. public surface
for addr in $non_loopback; do
  if timeout 2 bash -c "</dev/tcp/$addr/$STREAM_PORT" 2>/dev/null; then
    record "stream_port_public" "GREEN" "stream endpoint answers on $addr:$STREAM_PORT"
    break
  fi
done
if ! printf '%s\n' "${results[@]}" | grep -q stream_port_public; then
  record "stream_port_public" "RED" "nothing answers on :$STREAM_PORT on any global address"
fi

# ---------------------------------------------------------------- 4. profile volume
if mountpoint -q "$PROFILE_MOUNT" 2>/dev/null; then
  source_dev=$(findmnt -no SOURCE "$PROFILE_MOUNT" 2>/dev/null)
  if printf '%s' "$source_dev" | grep -q "^/dev/mapper/"; then
    record "profile_volume_encrypted" "GREEN" "mounted from $source_dev"
  else
    record "profile_volume_encrypted" "RED" "mounted from $source_dev, which is not a dm-crypt device"
  fi
else
  record "profile_volume_encrypted" "RED" "$PROFILE_MOUNT is not a mount point"
fi

# ---------------------------------------------------------------- 5. Chromium privileges
chromium_pid=$(systemctl show --property=MainPID --value "$CHROMIUM_UNIT" 2>/dev/null)
chromium_user=""
if [[ "$chromium_pid" =~ ^[1-9][0-9]*$ ]]; then
  chromium_user=$(ps -o user= -p "$chromium_pid" 2>/dev/null | tr -d ' ')
fi
if [ -z "$chromium_user" ]; then
  record "chromium_unprivileged" "UNKNOWN" "no actual process found for $CHROMIUM_UNIT"
elif [ "$chromium_user" != "$CHROMIUM_USER" ]; then
  record "chromium_unprivileged" "RED" "$CHROMIUM_UNIT runs as $chromium_user instead of the isolated $CHROMIUM_USER"
else
  record "chromium_unprivileged" "GREEN" "chromium runs as $chromium_user"
fi

if [ -z "$chromium_user" ]; then
  record "no_docker_socket_reach" "UNKNOWN" "no verified selected Chromium Unix identity"
elif [ ! -S /var/run/docker.sock ]; then
  record "no_docker_socket_reach" "GREEN" "no Docker Unix socket is present"
elif [ "$(id -u)" = 0 ] && command -v runuser >/dev/null 2>&1; then
  if runuser -u "$chromium_user" -- test -w /var/run/docker.sock; then
    record "no_docker_socket_reach" "RED" "$chromium_user can write to the Docker Unix socket"
  else
    record "no_docker_socket_reach" "GREEN" "the selected browser Unix identity has no socket write access"
  fi
elif [ "$(id -un)" = "$chromium_user" ]; then
  if [ -w /var/run/docker.sock ]; then
    record "no_docker_socket_reach" "RED" "$chromium_user can write to the Docker Unix socket"
  else
    record "no_docker_socket_reach" "GREEN" "the selected browser Unix identity has no socket write access"
  fi
else
  record "no_docker_socket_reach" "UNKNOWN" "cannot observe Docker socket access as the selected browser Unix identity"
fi

printf '{"host":"%s","checked_at":"%s","checks":[%s]}\n' \
  "$(hostname)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(IFS=,; echo "${results[*]}")"

exit "$overall"
