import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mutation import run

#: Every mutation this closure pass relied on, kept so the claim "N mutations caught" can
#: be re-checked rather than believed. Run from backend/:
#:
#:     python3 ../tools/audit/mutation_suite.py
ALL = [
 # --- checkpoint 5: the mission success contract ------------------------------
 (["tests/test_command_success_contract.py", "tests/test_verification_is_performed.py"], [
   ("van_gateway/command/success_contracts.py",
    'postconditions={"kill_switch_active": True, "owner_halt_active": True},',
    'postconditions={"kill_switch_active": True},',
    "C5 drop the owner-halt claim"),
   ("van_gateway/command/mission_link.py",
    "contract_for(resolution) if resolution is not None else SuccessContract()",
    "SuccessContract()", "C5 revert the joint"),
   ("van_gateway/verification/observations.py",
    'raise ValueError(str(status.get("ledger_stale_reason") or "the VATI ledger is stale"))',
    "pass", "C5 accept a stale ledger"),
   ("van_gateway/verification/observations.py", "if _is_absent(exc):", "if True:",
    "C5 unreachable provider reads as a deletion"),
   ("van_gateway/verification/observations.py",
    '"evidence_refs": [f"ledger://kill-switch/{head}"] if active and head else [],',
    '"evidence_refs": [f"ledger://kill-switch/{head}"],',
    "C5 cite evidence on a failed halt"),
 ]),
 # --- checkpoint 6: the computer-use fabric -----------------------------------
 (["tests/test_permissions_computeruse_verifiers.py", "tests/test_automation_health_api.py"], [
   ("van_gateway/computer_use/fabric.py",
    "SURFACE_WORKERS: frozenset[Surface] = frozenset()",
    "SURFACE_WORKERS: frozenset[Surface] = frozenset(Surface)",
    "C6 pretend every surface has a worker"),
   ("van_gateway/computer_use/fabric.py",
    "        if request.surface not in self.workers:", "        if False:",
    "C6 drop the no-worker refusal"),
   ("van_gateway/app.py",
    '"/v1/automation/health", "/v1/browser/health", "/v1/computer-use/health",\n        }:\n            return ControlScope.RUNTIME',
    '"/v1/automation/health", "/v1/browser/health",\n        }:\n            return ControlScope.RUNTIME',
    "C6 health route falls through to device auth"),
 ]),
 # --- checkpoint 7: learning ---------------------------------------------------
 (["tests/test_learning_records_and_bounds.py", "tests/test_ops_backup.py"], [
   ("van_gateway/evolution/radar.py",
    'if CLASS_RANK[ActionClass(str(row["max_action_class"]))] <= ceiling',
    "if True", "C7 offer every strategy regardless of envelope"),
   ("van_gateway/evolution/radar.py",
    'if CLASS_RANK[ActionClass(str(row["max_action_class"]))] < CLASS_RANK[max_action_class]:',
    "if False:", "C7 never raise the recorded ceiling"),
   # C7's original mutation targeted `verified_success=...`, the boolean that P1-LEARN-005
   # replaced. The successor is the classification table, mutated under RC2 below.
   ("van_gateway/learning/feed.py",
    "MissionState.VERIFIED_SUCCESS: StrategyOutcome.SUCCESS,",
    "MissionState.UNVERIFIABLE: StrategyOutcome.SUCCESS,",
    "C7 an unverified mission counts as a strategy success"),
   ("van_gateway/learning/feed.py", "if not sequence:\n            return None",
    "if False:\n            return None", "C7 strategy for a mission that ran nothing"),
   ("van_gateway/app.py",
    '        jobs.append(ScheduledJob(\n            "learning.auto_demote", settings.retention_interval_seconds, _demote_regressions,\n        ))',
    "        pass", "C7 drop the auto-demote job"),
   ("van_gateway/app.py",
    '        shutil.rmtree(workspace, ignore_errors=True)\n        return {\n            "ok": report["ok"],',
    '        return {\n            "ok": report["ok"],', "C7 leave the scratch restore on disk"),
   ("van_gateway/proactive/autonomy.py",
    "MAX_EARNED_LEVEL = AutonomyLevel.S2_PREPARE",
    "MAX_EARNED_LEVEL = AutonomyLevel.S5_MAINTAIN_DOMAIN",
    "C7 raise the earned-autonomy cap to the top"),
   ("van_gateway/learning/feed.py",
    'rows = await self.store.fetchall(\n            "SELECT capability_id FROM mission_activities',
    'await self.store.execute("UPDATE domain_trust SET owner_granted_ceiling = ?", ("S3",))\n'
    '        rows = await self.store.fetchall(\n            "SELECT capability_id FROM mission_activities',
    "C7 a learning module writes an authority table"),
 ]),
 # --- checkpoint 8: owner memory ----------------------------------------------
 (["tests/test_owner_memory_has_a_producer.py"], [
   ("van_gateway/mission/service.py",
    "            await self.learning.record_mission_opened(mission, now_ms=now)",
    "            pass", "C8 stop observing the goal"),
   ("van_gateway/learning/feed.py",
    "if mission.authority_envelope.requires_owner_presence:", "if True:",
    "C8 ordinary use recorded as a decision"),
   ("van_gateway/learning/feed.py", "                inferred_reason=None,",
    '                inferred_reason="the owner usually approves this",',
    "C8 infer a reason the owner never gave"),
   ("van_gateway/mission/service.py",
    "            await self.learning.record_decision_outcome(refreshed, state=refreshed.state)",
    "            pass", "C8 never record the decision outcome"),
   ("van_gateway/understanding/memory.py",
    "\"WHERE status = 'ACTIVE' AND latest_observed_ms < ?\"",
    "\"WHERE status = 'ACTIVE' AND latest_observed_ms >= ?\"",
    "C8 sweep the goals just mentioned"),
   ("van_gateway/app.py",
    '        jobs.append(ScheduledJob(\n            "understanding.mark_stale_intents", settings.retention_interval_seconds,\n            _mark_stale_intents,\n        ))',
    "        pass", "C8 drop the stale-intent sweep"),
 ]),
 # --- review corrections: semantic closure -------------------------------------
 # Every one of these is a counterexample in which the implementation looked green while
 # the owner's requested real-world outcome was false. Four of them describe defects that
 # were shipped and closed before an independent review found them.
 (["tests/test_command_success_contract.py", "tests/test_learning_records_and_bounds.py",
   "tests/test_owner_memory_has_a_producer.py"], [
   ("van_gateway/command/success_contracts.py",
    "    if action_id in _NOTEBOOK_SOURCE_ACTIONS:", "    if False:",
    "RC1 a source mutation falls back to the notebook contract"),
   ("van_gateway/command/success_contracts.py",
    '"sources_absent": [] if must_be_present else names,', '"sources_absent": [],',
    "RC1 a delete stops asserting the sources are gone"),
   ("van_gateway/command/success_contracts.py",
    '"sources_present": names if must_be_present else [],', '"sources_present": [],',
    "RC1 an add stops asserting the sources are there"),
   ("van_gateway/verification/observations.py",
    "            if not _is_absent(exc):\n                raise\n            absent.append(name)",
    "            absent.append(name)",
    "RC1 an unreachable provider reads as a removed source"),
   ("van_gateway/verification/production.py",
    '            raise ValueError(\n                "success contract names no notebook_id and source_names to read back"\n            )',
    "            return await observations.notebook_enterprise_readback(knowledge, str(postconditions.get('notebook_id') or 'x'))",
    "RC1 the source verifier falls back to the weaker notebook observation"),
   ("van_gateway/learning/feed.py",
    "MissionState.CANCELLED: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.CANCELLED: StrategyOutcome.FAILURE,",
    "RC2 an owner cancellation punishes the strategy"),
   ("van_gateway/learning/feed.py",
    "MissionState.UNVERIFIABLE: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.UNVERIFIABLE: StrategyOutcome.FAILURE,",
    "RC2 'VAN does not know' punishes the strategy"),
   ("van_gateway/learning/feed.py",
    "MissionState.BLOCKED_POLICY: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.BLOCKED_POLICY: StrategyOutcome.FAILURE,",
    "RC2 a policy refusal punishes the strategy"),
   ("van_gateway/evolution/radar.py",
    "        if outcome is StrategyOutcome.INCONCLUSIVE:", "        if False:",
    "RC2 inconclusive falls through to failure_count"),
   ("van_gateway/learning/feed.py",
    "MissionState.FAILED: StrategyOutcome.FAILURE,",
    "MissionState.FAILED: StrategyOutcome.INCONCLUSIVE,",
    "RC2 a real failure stops counting"),
   ("van_gateway/understanding/memory.py",
    "        if observations >= self.STANDING_AFTER_OBSERVATIONS:",
    "        if observations >= 1:",
    "RC4 one request becomes a standing goal again"),
   ("van_gateway/understanding/memory.py",
    "            current=IntentHorizon.EPHEMERAL,\n            observations=1,",
    "            current=IntentHorizon.STANDING,\n            observations=1,",
    "RC4 a brand-new goal starts standing"),
   ("van_gateway/understanding/memory.py",
    '            return IntentHorizon.STANDING, "the owner stated this is a standing goal"',
    "            return IntentHorizon.EPHEMERAL, None",
    "RC4 the owner saying so stops counting"),
 ]),
 # --- checkpoint 11: the recovery matrix ---------------------------------------
 (["tests/test_recovery_matrix.py"], [
   ("van_gateway/idempotency/service.py",
    'and now - int(row["updated_at_unix"]) >= STALE_CLAIM_SECONDS', "and True",
    "C11 release a claim the instant it is taken"),
   ("van_gateway/idempotency/service.py",
    'row["status"] == IdempotencyStatus.IN_FLIGHT.value\n                    and row["request_hash"] == req_hash',
    'row["request_hash"] == req_hash', "C11 a COMPLETED answer is retaken as work"),
   ("van_gateway/idempotency/service.py",
    '                    and row["request_hash"] == req_hash\n', "",
    "C11 retake a stale claim under a different request"),
   ("van_gateway/idempotency/service.py",
    "claim_count = claim_count + 1", "claim_count = claim_count",
    "C11 hide that a claim was recovered"),
   ("van_gateway/idempotency/service.py",
    '"UPDATE idempotency SET updated_at_unix = ?, "',
    '"UPDATE idempotency SET created_at_unix = ?, "',
    "C11 do not reset the lease when retaking"),
   ("van_gateway/mission/service.py",
    "        if current in TERMINAL_STATES:", "        if False:",
    "C11 accept a duplicate terminal callback"),
   ("van_gateway/mission/service.py",
    "        if target not in LEGAL_TRANSITIONS[current]:", "        if False:",
    "C11 accept a duplicate non-terminal callback"),
   ("van_gateway/mission/service.py",
    "        if expected is not None and expected is not current:", "        if False:",
    "C11 a racing writer with a stale expectation clobbers the state"),
   ("van_gateway/command/mission_link.py",
    "        if existing is not None:\n            return existing",
    "        if False:\n            return existing",
    "C11 open a second mission for a command that already has one"),
   ("van_gateway/learning/feed.py",
    "ON CONFLICT(outcome_id) DO UPDATE SET", "ON CONFLICT(outcome_id) DO NOTHING -- ",
    "C11 a replayed outcome row duplicates"),
   ("van_gateway/approval/service.py",
    'if int(record.get("expires_at_unix", 0)) <= now:', "if False:",
    "C11 an expired approval challenge can still be signed"),
   ("van_gateway/approval/service.py",
    'if device is None or device["revoked_at_unix"] is not None:', "if device is None:",
    "C11 a revoked device approves an A4 action"),
 ]),
 # --- checkpoint 16: the assumption gate ---------------------------------------
 (["tests/test_irreversible_work_waits_on_assumptions.py", "tests/test_authority_descriptor.py"], [
   ("van_gateway/runtime_api.py",
    "                await self._refuse_irreversible_work_on_unsettled_assumptions(\n                    definition, body.command_id\n                )\n",
    "", "C16 drop the gate from the execution ingress"),
   ("van_gateway/runtime_api.py",
    "        if descriptor.reversibility not in (\n            Reversibility.IRREVERSIBLE,\n            Reversibility.UNDECLARED,\n        ):",
    "        if descriptor.reversibility is not Reversibility.IRREVERSIBLE:",
    "C16 an undeclared reversibility is assumed reversible"),
   ("van_gateway/runtime_api.py",
    '            raise HTTPException(\n                status_code=409,\n                detail="irreversible_action_without_a_mission",\n            )',
    "            return", "C16 an action with no mission is waved through"),
   ("van_gateway/reasoning/kernel.py",
    "        if status in (AssumptionStatus.VERIFIED, AssumptionStatus.FALSIFIED) and not evidence_refs:",
    "        if status is AssumptionStatus.VERIFIED and not evidence_refs:",
    "C16 falsifying needs no evidence again"),
   ("van_gateway/reasoning/kernel.py",
    "        if status not in self.CALLER_RESOLVABLE:", "        if False:",
    "C16 a caller may assert expiry"),
   ("van_gateway/reasoning/kernel.py",
    "            if not superseded_by:\n                raise ReasoningError(\"SUPERSEDED_REQUIRES_A_REPLACEMENT\", assumption_id)",
    "            if False:\n                raise ReasoningError(\"SUPERSEDED_REQUIRES_A_REPLACEMENT\", assumption_id)",
    "C16 supersession need not name a replacement"),
   ("van_gateway/reasoning/kernel.py",
    '            if str(replacement["mission_id"]) != str(original["mission_id"]):',
    "            if False:", "C16 cite another mission's assumption as the replacement"),
   ("van_gateway/reasoning/kernel.py",
    "            if superseded_by == assumption_id:", "            if False:",
    "C16 an assumption supersedes itself"),
   ("van_gateway/reasoning/kernel.py",
    "            return int(cursor.rowcount or 0)", "            return 0",
    "C16 expiry reports a count that is always zero"),
   ("van_gateway/orchestrator.py", "        required_gate = gate_for(effective_action_class)",
    "        required_gate = Gate.DEVICE_SIGNATURE",
    "C16 the orchestrator stops asking the descriptor"),
   ("van_gateway/orchestrator.py", "        if required_gate is Gate.OWNER_APPROVAL:",
    "        if False:", "C16 A4 no longer needs owner approval"),
   ("van_gateway/orchestrator.py", "        if required_gate is Gate.FORBIDDEN:",
    "        if False:", "C16 A5 is no longer refused"),
 ]),
 # --- checkpoint 9: evolution --------------------------------------------------
 (["tests/test_external_reality_and_benchmarks.py"], [
   ("van_gateway/research/exa.py", "            if source.title:", "            if False:",
    "C9 stop recording what sources claim"),
   ("van_gateway/research/exa.py", "                    contradicts_owner_belief=False,",
    "                    contradicts_owner_belief=True,",
    "C9 decide the owner is wrong from a headline"),
   ("van_gateway/research/exa.py", "                    confidence=0.0,",
    "                    confidence=0.9,", "C9 untrusted source looks credible"),
   ("van_gateway/evolution/radar.py",
    "    SUITES_WITH_A_CORPUS: frozenset[str] = frozenset()",
    "    SUITES_WITH_A_CORPUS: frozenset[str] = frozenset(SUITES)",
    "C9 claim every suite has a corpus"),
   ("van_gateway/evolution/radar.py", "            if not record.admissible:", "            if False:",
    "C9 admit a technology with no benchmark"),
 ]),
 # --- checkpoint 13: owner context lifecycle governance -----------------------
 (["tests/test_context_lifecycle_governance.py"], [
   ("van_gateway/context/lifecycle.py", '"truncated": held > len(exported),',
    '"truncated": False,', "C13 hide that the export was cut short"),
   ("van_gateway/context/lifecycle.py", "            stores[entry.table] = {",
    "            if entry.table != \"owner_facts\":\n                continue\n            stores[entry.table] = {",
    "C13 export only the store that was already exportable"),
   ("van_gateway/context/service.py", "                    candidate.supersedes_fact_id,\n",
    "                    None,\n", "C13 drop the fact supersession link again"),
   ("van_gateway/context/service.py",
    "candidate.sensitivity.value, revision, candidate.supersedes_edge_id,",
    "candidate.sensitivity.value, revision, None,",
    "C13 drop the edge supersession link again"),
   ("van_gateway/context/lifecycle.py",
    "                superseded_by_fact_id=replaced_by.get(record.fact_id),",
    "                superseded_by_fact_id=None,",
    "C13 lose the forward direction of the chain"),
   ("van_gateway/context/lifecycle.py",
    "                if r.valid_until_ms is not None and r.superseded_by_fact_id is None",
    "                if r.valid_until_ms is not None",
    "C13 report a correction as a withdrawal"),
   ("van_gateway/context/lifecycle.py",
    "            ORDER BY valid_from_ms DESC, revision DESC", "            ORDER BY rowid ASC",
    "C13 order history by insertion instead of belief"),
   ("van_gateway/context/lifecycle.py",
    "            if loose.state is ReadinessState.CONFLICTED:", "            if False:",
    "C13 stop reporting inference-only contradictions"),
   ("van_gateway/context/lifecycle.py",
    "                    subject=subject, predicate=predicate, scope=scope, allow_inferred=False",
    "                    subject=subject, predicate=predicate, scope=scope, allow_inferred=True",
    "C13 report inference conflicts as blocking"),
   ("van_gateway/context/lifecycle.py", '            "sides": sides,',
    '            "sides": [s["fact_id"] for s in sides],',
    "C13 report ids without the values that disagree"),
   ("van_gateway/app.py",
    '            result="ok", device_id=device_id, capability="context.export",',
    '            result="ok", device_id=device_id, capability="context.read",',
    "C13 bulk read of the owner graph leaves no matching trace"),
 ]),
]

APP_KT = "android/app/src/main/java/com/dial/van"
ENV_KT = f"{APP_KT}/runtime/VanResourceEnvelope.kt"
EVT_KT = f"{APP_KT}/events/EventStream.kt"

#: Mutations against files outside backend/ — the workflow, the Gradle scripts — checked by
#: contract tests that run from the repository root. Kept separate rather than folded into
#: ALL because both the mutation root and pytest's working directory differ.
ROOT_LEVEL = [
 # --- checkpoint 15: the Kotlin reachability scanner ---------------------------
 # A scanner is only as good as what it refuses to count. The first four here are the
 # manifest parse and the three ways a symbol can appear without being a call site; a
 # sweep that counts a KDoc mention makes every well-documented dead class look alive,
 # which is the confusion this whole programme exists to correct.
 (["tests/contracts/test_kotlin_reachability.py"], [
   ("tools/audit/kotlin_reachability.py",
    'r"<(?:activity|activity-alias|service|receiver|provider|application)\\b[^>]*?"\n    r\'android:name="\\.?([A-Za-z0-9_.]+)"\'',
    'r\'android:name="\\.?([A-Za-z0-9_.]+)"\'',
    "C15 the manifest sweep treats permissions as components again"),
   ("tools/audit/kotlin_reachability.py", '    text = re.sub(r"//[^\\n]*", " ", text)', "    pass",
    "C15 a symbol named in a line comment counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    '    text = re.sub(r"/\\*.*?\\*/", " ", text, flags=re.DOTALL)', "    pass",
    "C15 a symbol named in a KDoc counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    """    text = re.sub(r'"(?:[^"\\\\\\n]|\\\\.)*"', ' "" ', text)""", "    pass",
    "C15 a symbol named in a string counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    '    text = re.sub(r"//[^\\n]*", " ", text)', '    text = re.sub(r".*", " ", text)',
    "C15 strip everything, so all code looks dead"),
   ("tools/audit/kotlin_reachability.py",
    'r"(?:(?:enum|annotation|companion)\\s+)?"', '""',
    "C15 miss enum and annotation declarations"),
   ("tools/audit/kotlin_reachability.py",
    "        if not reached_by and not reached_by_tests:", "        if False:",
    "C15 stop reporting files nothing references"),
   ("tools/audit/kotlin_reachability.py",
    "        elif not reached_by and reached_by_tests:", "        elif False:",
    "C15 stop reporting test-only symbols"),
 ]),
 # --- checkpoint 14: the runtime envelope's wiring ----------------------------
 # The envelope's arithmetic is mutated under Gradle (see KOTLIN below). These are the
 # Python half: whether anything in the shipping app actually asks it. A fully tested
 # envelope that no production path reaches is the audit's most common defect shape.
 (["tests/contracts/test_the_runtime_envelope_governs.py"], [
   (f"{APP_KT}/visual/VanCanvasFallback.kt", "VanResourceEnvelope.effectBudget(",
    "VanEffectPolicy.resolve(", "C14 the embodiment resolves its own budget again"),
   (f"{APP_KT}/command/modules/WorkModules.kt",
    "stream, truncated, DeviceRuntimeReadings.pressure(context),", "stream, truncated,",
    "C14 the poll loop takes the default pressure"),
   (f"{APP_KT}/telemetry/DeviceTelemetryReporter.kt",
    "delay((FLUSH_INTERVAL_MS * allowance.cadenceScale).toLong())", "delay(FLUSH_INTERVAL_MS)",
    "C14 the flush interval ignores the allowance"),
   (f"{APP_KT}/command/modules/WorkModules.kt", ") ?: break", ") ?: 0L",
    "C14 a stop is coerced back into a delay"),
   (f"{APP_KT}/runtime/VanResourceEnvelope.kt",
    "        VanSubsystem.WAKE_WORD,\n        VanSubsystem.OWNER_COMMAND,\n        VanSubsystem.DEGRADED_REPORTING,\n",
    "", "C14 empty the never-shed set"),
   (f"{APP_KT}/runtime/VanResourceEnvelope.kt", "const val UNKNOWN = -1", "const val UNKNOWN = 0",
    "C14 an unreadable battery reads as flat"),
   (f"{APP_KT}/runtime/DeviceRuntimeReadings.kt", "context.filesDir.usableSpace", "0L",
    "C14 stop reading free storage"),
 ]),
 # --- checkpoint 12: the APK leaves CI ----------------------------------------
 (["tests/contracts/test_the_apk_leaves_ci.py",
   "tests/contracts/test_ci_workflow_is_what_it_claims.py"], [
   (".github/workflows/van-ci.yml",
    """      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: van-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
""", "", "C12 drop the APK upload entirely"),
   (".github/workflows/van-ci.yml", "if-no-files-found: error\n      - name: Shared visual",
    "if-no-files-found: warn\n      - name: Shared visual",
    "C12 publish an empty artefact instead of failing"),
   (".github/workflows/van-ci.yml", "path: android/app/build/outputs/apk/debug/*.apk",
    "path: android/app/build/outputs/apk/release/*.apk",
    "C12 point the upload at a variant the build never assembles"),
   (".github/workflows/van-ci.yml",
    "./gradlew :app:testDebugUnitTest :app:assembleDebug :app:lintDebug",
    "./gradlew :app:testDebugUnitTest :app:lintDebug",
    "C12 stop assembling the APK but keep uploading it"),
   ("android/settings.gradle.kts", 'include(":app")', 'include(":application")',
    "C12 rename the module out from under the artifact path"),
   ("android/app/build.gradle.kts", 'id("com.android.application")',
    'id("com.android.library")', "C12 a module that emits an AAR, not an APK"),
 ]),
]

#: Checkpoint 14, Kotlin half. Run by Gradle in android/verification rather than by pytest,
#: because that harness is the only thing in this repository that can execute Kotlin at all.
KOTLIN = [
 (ENV_KT, "status >= THERMAL_CRITICAL -> RuntimePressure.SURVIVAL",
  "status >= THERMAL_CRITICAL -> RuntimePressure.NOMINAL",
  "C14 thermal critical reads as fine"),
 ([(ENV_KT, '            add("thermal" to thermalPressure(reading.thermalStatus))',
    '            if (!reading.charging) add("thermal" to thermalPressure(reading.thermalStatus))')],
  "C14 being on a charger excuses the heat"),
 (ENV_KT, "        val pressure = contributions.maxOf { it.second }",
  "        val pressure = contributions.last().second",
  "C14 pressure is the last input rather than the worst"),
 # Compound: the never-shed promise is held by a guard clause and by the table it guards,
 # so neither edit alone changes behaviour. A single-edit mutation surviving for that reason
 # would say nothing about whether the promise is tested.
 ([(ENV_KT, "        if (subsystem in NEVER_SHED) return Allowance.FULL",
    "        if (false) return Allowance.FULL"),
   (ENV_KT, """            VanSubsystem.WAKE_WORD,
            VanSubsystem.OWNER_COMMAND,
            VanSubsystem.DEGRADED_REPORTING,
            -> Allowance.FULL""",
    """            VanSubsystem.WAKE_WORD,
            VanSubsystem.OWNER_COMMAND,
            VanSubsystem.DEGRADED_REPORTING,
            -> if (pressure.atLeast(RuntimePressure.CRITICAL)) Allowance.STOPPED else Allowance.FULL""")],
  "C14 the wake word is shed under pressure"),
 (ENV_KT, "        VanEffectBudget.REDUCED_MOTION -> 1", "        VanEffectBudget.REDUCED_MOTION -> 3",
  "C14 reduced motion ranked as rich, so pressure clamps it into a moving budget"),
 (ENV_KT, "        return if (rank(ladder) <= rank(ceiling)) ladder else ceiling",
  "        return if (rank(ladder) >= rank(ceiling)) ladder else ceiling",
  "C14 the envelope raises the embodiment's budget"),
 (ENV_KT,
  "                pressure.atLeast(RuntimePressure.CRITICAL) -> Allowance.STOPPED\n                pressure.atLeast(RuntimePressure.CONSTRAINED) -> Allowance(true, 4.0)",
  "                pressure.atLeast(RuntimePressure.CRITICAL) -> Allowance(false, 4.0)\n                pressure.atLeast(RuntimePressure.CONSTRAINED) -> Allowance(true, 4.0)",
  "C14 a stopped subsystem keeps a cadence"),
 (EVT_KT, "    const val CATCH_UP_POLL_MS = 0L", "    const val CATCH_UP_POLL_MS = 500L",
  "C14 catch-up stops being immediate, so pressure now stretches it"),
 (EVT_KT, "        return (base * allowance.cadenceScale).toLong().coerceAtMost(MAX_BACKOFF_MS)",
  "        return (base * allowance.cadenceScale).toLong()",
  "C14 a stretched backoff exceeds the ceiling"),
 (EVT_KT, "        if (!allowance.running) return null", "        if (false) return null",
  "C14 SURVIVAL keeps polling"),
]

ROOT = pathlib.Path(__file__).resolve().parents[2]

survivors = []
for tests, mutations in ALL:
    print(f"\n### {tests}")
    survivors += run(mutations, tests)
for tests, mutations in ROOT_LEVEL:
    print(f"\n### {tests}")
    survivors += run(mutations, tests, root=ROOT, cwd=ROOT)

print("\n### android/verification (Gradle)")
survivors += run(
    KOTLIN, [], root=ROOT, cwd=ROOT / "android" / "verification",
    command=["gradle", "test", "--console=plain", "--offline", "--rerun-tasks"],
)
print("\n================ SURVIVORS ================")
print("\n".join(survivors) or "none")
