import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mutation import run

#: Every mutation this closure pass relied on, kept so the claim "N mutations caught" can
#: be re-checked rather than believed. Run from backend/:
#:
#:     python3 ../tools/audit/mutation_suite.py
ALL = [
 # --- checkpoint 5: the mission success contract ------------------------------
 (["tests/test_command_success_contract.py", "tests/test_verification_is_performed.py"], [
   ("van_gateway/command/success_contracts.py",
    'postconditions={"kill_switch_active": True, "owner_halt_active": True},',
    'postconditions={"kill_switch_active": True},',
    "C5 drop the owner-halt claim"),
   ("van_gateway/command/mission_link.py",
    "contract_for(resolution) if resolution is not None else SuccessContract()",
    "SuccessContract()", "C5 revert the joint"),
   ("van_gateway/verification/observations.py",
    'raise ValueError(str(status.get("ledger_stale_reason") or "the VATI ledger is stale"))',
    "pass", "C5 accept a stale ledger"),
   ("van_gateway/verification/observations.py", "if _is_absent(exc):", "if True:",
    "C5 unreachable provider reads as a deletion"),
   ("van_gateway/verification/observations.py",
    '"evidence_refs": [f"ledger://kill-switch/{head}"] if active and head else [],',
    '"evidence_refs": [f"ledger://kill-switch/{head}"],',
    "C5 cite evidence on a failed halt"),
 ]),
 # --- checkpoint 6: the computer-use fabric -----------------------------------
 (["tests/test_permissions_computeruse_verifiers.py", "tests/test_automation_health_api.py"], [
   ("van_gateway/computer_use/fabric.py",
    "SURFACE_WORKERS: frozenset[Surface] = frozenset()",
    "SURFACE_WORKERS: frozenset[Surface] = frozenset(Surface)",
    "C6 pretend every surface has a worker"),
   ("van_gateway/computer_use/fabric.py",
    "        if request.surface not in self.workers:", "        if False:",
    "C6 drop the no-worker refusal"),
   ("van_gateway/app.py",
    '"/v1/automation/health", "/v1/browser/health", "/v1/computer-use/health",\n        }:\n            return ControlScope.RUNTIME',
    '"/v1/automation/health", "/v1/browser/health",\n        }:\n            return ControlScope.RUNTIME',
    "C6 health route falls through to device auth"),
 ]),
 # --- checkpoint 7: learning ---------------------------------------------------
 (["tests/test_learning_records_and_bounds.py", "tests/test_ops_backup.py"], [
   ("van_gateway/evolution/radar.py",
    'if CLASS_RANK[ActionClass(str(row["max_action_class"]))] <= ceiling',
    "if True", "C7 offer every strategy regardless of envelope"),
   ("van_gateway/evolution/radar.py",
    'if CLASS_RANK[ActionClass(str(row["max_action_class"]))] < CLASS_RANK[max_action_class]:',
    "if False:", "C7 never raise the recorded ceiling"),
   # C7's original mutation targeted `verified_success=...`, the boolean that P1-LEARN-005
   # replaced. The successor is the classification table, mutated under RC2 below.
   ("van_gateway/learning/feed.py",
    "MissionState.VERIFIED_SUCCESS: StrategyOutcome.SUCCESS,",
    "MissionState.UNVERIFIABLE: StrategyOutcome.SUCCESS,",
    "C7 an unverified mission counts as a strategy success"),
   ("van_gateway/learning/feed.py", "if not sequence:\n            return None",
    "if False:\n            return None", "C7 strategy for a mission that ran nothing"),
   ("van_gateway/app.py",
    '        jobs.append(ScheduledJob(\n            "learning.auto_demote", settings.retention_interval_seconds, _demote_regressions,\n        ))',
    "        pass", "C7 drop the auto-demote job"),
   ("van_gateway/app.py",
    '        shutil.rmtree(workspace, ignore_errors=True)\n        return {\n            "ok": report["ok"],',
    '        return {\n            "ok": report["ok"],', "C7 leave the scratch restore on disk"),
   ("van_gateway/proactive/autonomy.py",
    "MAX_EARNED_LEVEL = AutonomyLevel.S2_PREPARE",
    "MAX_EARNED_LEVEL = AutonomyLevel.S5_MAINTAIN_DOMAIN",
    "C7 raise the earned-autonomy cap to the top"),
   ("van_gateway/learning/feed.py",
    'rows = await self.store.fetchall(\n            "SELECT capability_id FROM mission_activities',
    'await self.store.execute("UPDATE domain_trust SET owner_granted_ceiling = ?", ("S3",))\n'
    '        rows = await self.store.fetchall(\n            "SELECT capability_id FROM mission_activities',
    "C7 a learning module writes an authority table"),
 ]),
 # --- checkpoint 8: owner memory ----------------------------------------------
 (["tests/test_owner_memory_has_a_producer.py"], [
   ("van_gateway/mission/service.py",
    "            await self.learning.record_mission_opened(mission, now_ms=now)",
    "            pass", "C8 stop observing the goal"),
   ("van_gateway/learning/feed.py",
    "if mission.authority_envelope.requires_owner_presence:", "if True:",
    "C8 ordinary use recorded as a decision"),
   ("van_gateway/learning/feed.py", "                inferred_reason=None,",
    '                inferred_reason="the owner usually approves this",',
    "C8 infer a reason the owner never gave"),
   ("van_gateway/mission/service.py",
    "            await self.learning.record_decision_outcome(refreshed, state=refreshed.state)",
    "            pass", "C8 never record the decision outcome"),
   ("van_gateway/understanding/memory.py",
    "\"WHERE status = 'ACTIVE' AND latest_observed_ms < ?\"",
    "\"WHERE status = 'ACTIVE' AND latest_observed_ms >= ?\"",
    "C8 sweep the goals just mentioned"),
   ("van_gateway/app.py",
    '        jobs.append(ScheduledJob(\n            "understanding.mark_stale_intents", settings.retention_interval_seconds,\n            _mark_stale_intents,\n        ))',
    "        pass", "C8 drop the stale-intent sweep"),
 ]),
 # --- review corrections: semantic closure -------------------------------------
 # Every one of these is a counterexample in which the implementation looked green while
 # the owner's requested real-world outcome was false. Four of them describe defects that
 # were shipped and closed before an independent review found them.
 (["tests/test_command_success_contract.py", "tests/test_learning_records_and_bounds.py",
   "tests/test_owner_memory_has_a_producer.py"], [
   ("van_gateway/command/success_contracts.py",
    "    if action_id in _NOTEBOOK_SOURCE_ACTIONS:", "    if False:",
    "RC1 a source mutation falls back to the notebook contract"),
   ("van_gateway/command/success_contracts.py",
    '"sources_absent": [] if must_be_present else names,', '"sources_absent": [],',
    "RC1 a delete stops asserting the sources are gone"),
   ("van_gateway/command/success_contracts.py",
    '"sources_present": names if must_be_present else [],', '"sources_present": [],',
    "RC1 an add stops asserting the sources are there"),
   ("van_gateway/verification/observations.py",
    "            if not _is_absent(exc):\n                raise\n            absent.append(name)",
    "            absent.append(name)",
    "RC1 an unreachable provider reads as a removed source"),
   ("van_gateway/verification/production.py",
    '            raise ValueError(\n                "success contract names no notebook_id and source_names to read back"\n            )',
    "            return await observations.notebook_enterprise_readback(knowledge, str(postconditions.get('notebook_id') or 'x'))",
    "RC1 the source verifier falls back to the weaker notebook observation"),
   ("van_gateway/learning/feed.py",
    "MissionState.CANCELLED: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.CANCELLED: StrategyOutcome.FAILURE,",
    "RC2 an owner cancellation punishes the strategy"),
   ("van_gateway/learning/feed.py",
    "MissionState.UNVERIFIABLE: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.UNVERIFIABLE: StrategyOutcome.FAILURE,",
    "RC2 'VAN does not know' punishes the strategy"),
   ("van_gateway/learning/feed.py",
    "MissionState.BLOCKED_POLICY: StrategyOutcome.INCONCLUSIVE,",
    "MissionState.BLOCKED_POLICY: StrategyOutcome.FAILURE,",
    "RC2 a policy refusal punishes the strategy"),
   ("van_gateway/evolution/radar.py",
    "        if outcome is StrategyOutcome.INCONCLUSIVE:", "        if False:",
    "RC2 inconclusive falls through to failure_count"),
   ("van_gateway/learning/feed.py",
    "MissionState.FAILED: StrategyOutcome.FAILURE,",
    "MissionState.FAILED: StrategyOutcome.INCONCLUSIVE,",
    "RC2 a real failure stops counting"),
   ("van_gateway/understanding/memory.py",
    "        if observations >= self.STANDING_AFTER_OBSERVATIONS:",
    "        if observations >= 1:",
    "RC4 one request becomes a standing goal again"),
   ("van_gateway/understanding/memory.py",
    "            current=IntentHorizon.EPHEMERAL,\n            observations=1,",
    "            current=IntentHorizon.STANDING,\n            observations=1,",
    "RC4 a brand-new goal starts standing"),
   ("van_gateway/understanding/memory.py",
    '            return IntentHorizon.STANDING, "the owner stated this is a standing goal"',
    "            return IntentHorizon.EPHEMERAL, None",
    "RC4 the owner saying so stops counting"),
 ]),
 # --- checkpoint 11: the recovery matrix ---------------------------------------
 (["tests/test_recovery_matrix.py"], [
   ("van_gateway/idempotency/service.py",
    'and now - int(row["updated_at_unix"]) >= STALE_CLAIM_SECONDS', "and True",
    "C11 release a claim the instant it is taken"),
   ("van_gateway/idempotency/service.py",
    'row["status"] == IdempotencyStatus.IN_FLIGHT.value\n                    and row["request_hash"] == req_hash',
    'row["request_hash"] == req_hash', "C11 a COMPLETED answer is retaken as work"),
   ("van_gateway/idempotency/service.py",
    '                    and row["request_hash"] == req_hash\n', "",
    "C11 retake a stale claim under a different request"),
   ("van_gateway/idempotency/service.py",
    "claim_count = claim_count + 1", "claim_count = claim_count",
    "C11 hide that a claim was recovered"),
   ("van_gateway/idempotency/service.py",
    '"UPDATE idempotency SET updated_at_unix = ?, "',
    '"UPDATE idempotency SET created_at_unix = ?, "',
    "C11 do not reset the lease when retaking"),
   ("van_gateway/mission/service.py",
    "        if current in TERMINAL_STATES:", "        if False:",
    "C11 accept a duplicate terminal callback"),
   ("van_gateway/mission/service.py",
    "        if target not in LEGAL_TRANSITIONS[current]:", "        if False:",
    "C11 accept a duplicate non-terminal callback"),
   ("van_gateway/mission/service.py",
    "        if expected is not None and expected is not current:", "        if False:",
    "C11 a racing writer with a stale expectation clobbers the state"),
   ("van_gateway/command/mission_link.py",
    "        if existing is not None:\n            return existing",
    "        if False:\n            return existing",
    "C11 open a second mission for a command that already has one"),
   ("van_gateway/learning/feed.py",
    "ON CONFLICT(outcome_id) DO UPDATE SET", "ON CONFLICT(outcome_id) DO NOTHING -- ",
    "C11 a replayed outcome row duplicates"),
   ("van_gateway/approval/service.py",
    'if int(record.get("expires_at_unix", 0)) <= now:', "if False:",
    "C11 an expired approval challenge can still be signed"),
   ("van_gateway/approval/service.py",
    'if device is None or device["revoked_at_unix"] is not None:', "if device is None:",
    "C11 a revoked device approves an A4 action"),
 ]),
 # --- checkpoint 17: the rule that lived only in dead code ---------------------
 (["tests/test_epistemics_context_understanding.py"], [
   ("van_gateway/context/service.py",
    "            and selected.authority not in _NOT_STALE_ON_A_CLOCK\n", "",
    "C17 the owner's own statement goes stale on a clock again"),
   ("van_gateway/context/service.py",
    "_NOT_STALE_ON_A_CLOCK = {\n    EpistemicState.CANONICAL_OWNER,\n    EpistemicState.PROJECT_TRUTH,\n}",
    "_NOT_STALE_ON_A_CLOCK = set(EpistemicState)",
    "C17 exempt everything, so max_age_ms means nothing"),
   ("van_gateway/context/service.py",
    "              AND valid_from_ms <= ?\n              AND (valid_until_ms IS NULL OR valid_until_ms > ?)",
    "              AND valid_from_ms <= ?\n              AND (1 = 1 OR valid_until_ms > ?)",
    "C17 an owner statement the owner scoped never ends"),
 ]),
 # --- checkpoint 16: the assumption gate ---------------------------------------
 (["tests/test_irreversible_work_waits_on_assumptions.py", "tests/test_authority_descriptor.py"], [
   ("van_gateway/runtime_api.py",
    "                await self._refuse_irreversible_work_on_unsettled_assumptions(\n                    definition, body.command_id\n                )\n",
    "", "C16 drop the gate from the execution ingress"),
   ("van_gateway/runtime_api.py",
    "        if descriptor.reversibility not in (\n            Reversibility.IRREVERSIBLE,\n            Reversibility.UNDECLARED,\n        ):",
    "        if descriptor.reversibility is not Reversibility.IRREVERSIBLE:",
    "C16 an undeclared reversibility is assumed reversible"),
   ("van_gateway/runtime_api.py",
    '            raise HTTPException(\n                status_code=409,\n                detail="irreversible_action_without_a_mission",\n            )',
    "            return", "C16 an action with no mission is waved through"),
   ("van_gateway/reasoning/kernel.py",
    "        if status in (AssumptionStatus.VERIFIED, AssumptionStatus.FALSIFIED) and not evidence_refs:",
    "        if status is AssumptionStatus.VERIFIED and not evidence_refs:",
    "C16 falsifying needs no evidence again"),
   ("van_gateway/reasoning/kernel.py",
    "        if status not in self.CALLER_RESOLVABLE:", "        if False:",
    "C16 a caller may assert expiry"),
   ("van_gateway/reasoning/kernel.py",
    "            if not superseded_by:\n                raise ReasoningError(\"SUPERSEDED_REQUIRES_A_REPLACEMENT\", assumption_id)",
    "            if False:\n                raise ReasoningError(\"SUPERSEDED_REQUIRES_A_REPLACEMENT\", assumption_id)",
    "C16 supersession need not name a replacement"),
   ("van_gateway/reasoning/kernel.py",
    '            if str(replacement["mission_id"]) != str(original["mission_id"]):',
    "            if False:", "C16 cite another mission's assumption as the replacement"),
   ("van_gateway/reasoning/kernel.py",
    "            if superseded_by == assumption_id:", "            if False:",
    "C16 an assumption supersedes itself"),
   ("van_gateway/reasoning/kernel.py",
    "            return int(cursor.rowcount or 0)", "            return 0",
    "C16 expiry reports a count that is always zero"),
   ("van_gateway/orchestrator.py", "        required_gate = gate_for(effective_action_class)",
    "        required_gate = Gate.DEVICE_SIGNATURE",
    "C16 the orchestrator stops asking the descriptor"),
   ("van_gateway/orchestrator.py", "        if required_gate is Gate.OWNER_APPROVAL:",
    "        if False:", "C16 A4 no longer needs owner approval"),
   ("van_gateway/orchestrator.py", "        if required_gate is Gate.FORBIDDEN:",
    "        if False:", "C16 A5 is no longer refused"),
 ]),
 # --- checkpoint 9: evolution --------------------------------------------------
 (["tests/test_external_reality_and_benchmarks.py"], [
   ("van_gateway/research/exa.py", "            if source.title:", "            if False:",
    "C9 stop recording what sources claim"),
   ("van_gateway/research/exa.py", "                    contradicts_owner_belief=False,",
    "                    contradicts_owner_belief=True,",
    "C9 decide the owner is wrong from a headline"),
   ("van_gateway/research/exa.py", "                    confidence=0.0,",
    "                    confidence=0.9,", "C9 untrusted source looks credible"),
   ("van_gateway/evolution/radar.py",
    "    SUITES_WITH_A_CORPUS: frozenset[str] = frozenset()",
    "    SUITES_WITH_A_CORPUS: frozenset[str] = frozenset(SUITES)",
    "C9 claim every suite has a corpus"),
   ("van_gateway/evolution/radar.py", "            if not record.admissible:", "            if False:",
    "C9 admit a technology with no benchmark"),
 ]),
 # --- checkpoint 13: owner context lifecycle governance -----------------------
 (["tests/test_context_lifecycle_governance.py"], [
   ("van_gateway/context/lifecycle.py", '"truncated": held > len(exported),',
    '"truncated": False,', "C13 hide that the export was cut short"),
   ("van_gateway/context/lifecycle.py", "            stores[entry.table] = {",
    "            if entry.table != \"owner_facts\":\n                continue\n            stores[entry.table] = {",
    "C13 export only the store that was already exportable"),
   ("van_gateway/context/service.py", "                    candidate.supersedes_fact_id,\n",
    "                    None,\n", "C13 drop the fact supersession link again"),
   ("van_gateway/context/service.py",
    "candidate.sensitivity.value, revision, candidate.supersedes_edge_id,",
    "candidate.sensitivity.value, revision, None,",
    "C13 drop the edge supersession link again"),
   ("van_gateway/context/lifecycle.py",
    "                superseded_by_fact_id=replaced_by.get(record.fact_id),",
    "                superseded_by_fact_id=None,",
    "C13 lose the forward direction of the chain"),
   ("van_gateway/context/lifecycle.py",
    "                if r.valid_until_ms is not None and r.superseded_by_fact_id is None",
    "                if r.valid_until_ms is not None",
    "C13 report a correction as a withdrawal"),
   ("van_gateway/context/lifecycle.py",
    "            ORDER BY valid_from_ms DESC, revision DESC", "            ORDER BY rowid ASC",
    "C13 order history by insertion instead of belief"),
   ("van_gateway/context/lifecycle.py",
    "            if loose.state is ReadinessState.CONFLICTED:", "            if False:",
    "C13 stop reporting inference-only contradictions"),
   ("van_gateway/context/lifecycle.py",
    "                    subject=subject, predicate=predicate, scope=scope, allow_inferred=False",
    "                    subject=subject, predicate=predicate, scope=scope, allow_inferred=True",
    "C13 report inference conflicts as blocking"),
   ("van_gateway/context/lifecycle.py", '            "sides": sides,',
    '            "sides": [s["fact_id"] for s in sides],',
    "C13 report ids without the values that disagree"),
   ("van_gateway/app.py",
    '            result="ok", device_id=device_id, capability="context.export",',
    '            result="ok", device_id=device_id, capability="context.read",',
    "C13 bulk read of the owner graph leaves no matching trace"),
 ]),
 # --- checkpoint 23: the interactive browser session -----------------------------
 #
 # The two control-lease entries are separate on purpose. A first pass tested preemption
 # only, where the lease id and the generation both change, so deleting either comparison
 # survived: two guards that always fire together are one guard, and nobody knows which.
 # The suite drives each in isolation now.
 (["tests/test_interactive_browser_session.py"], [
   ("van_gateway/browser/control_lease.py",
    '        if lease.generation != int(control_generation):\n            raise ControlLeaseError("control_generation_stale")',
    '        if False:\n            raise ControlLeaseError("control_generation_stale")',
    "C23 a stale control generation actuates"),
   ("van_gateway/browser/control_lease.py",
    '        if lease.control_lease_id != control_lease_id:\n            raise ControlLeaseError("control_lease_superseded")',
    '        if False:\n            raise ControlLeaseError("control_lease_superseded")',
    "C23 a fabricated control lease id actuates"),
   ("van_gateway/browser/control_lease.py",
    '            generation = int((await cur.fetchone())["g"]) + 1',
    "            generation = 1",
    "C23 the control fence never moves"),
   ("van_gateway/browser/interactive_service.py",
    '        if session.acked_viewport_revision != session.viewport.revision:\n            raise InteractiveSessionError("interactive_viewport_not_acknowledged")',
    '        if False:\n            raise InteractiveSessionError("interactive_viewport_not_acknowledged")',
    "C23 input lands before the device acknowledges the layout"),
   ("van_gateway/browser/interactive_service.py",
    "        if int(viewport_revision) != session.viewport.revision:",
    "        if False:",
    "C23 a stale viewport revision actuates"),
   ("van_gateway/browser/service.py",
    '        if int(row["lease_expires_at_ms"] or 0) <= now:\n            raise BrowserPolicyError("browser_profile_lease_expired")',
    '        if int(row["lease_expires_at_ms"] or 0) + 30_000 <= now:\n            raise BrowserPolicyError("browser_profile_lease_expired")',
    "C23 the cleanup grace extends actuation authority"),
   ("van_gateway/browser/stream_grants.py",
    '        if header.get("alg") != "ES256":',
    "        if False:",
    "C23 the grant verifier accepts the algorithm the token names"),
   ("van_gateway/browser/stream_grants.py",
    "                 WHERE nonce = ? AND redeemed_at_ms IS NULL AND revoked_at_ms IS NULL",
    "                 WHERE nonce = ? AND revoked_at_ms IS NULL",
    "C23 a stream grant is redeemable twice"),
   ("van_gateway/events/bus.py",
    "                   AND (target_device_id IS NULL OR target_device_id = ?)",
    "                   AND (target_device_id IS NULL OR target_device_id IS NOT NULL OR target_device_id = ?)",
    "C23 one device\'s events reach another device"),
   ("van_gateway/events/bus.py",
    'last = events[-1]["seq"] if truncated else max(ceiling, after_seq)',
    'last = events[-1]["seq"] if events else max(ceiling, after_seq)',
    "C23 the cursor sticks behind another device\'s rows"),
 ]),
 # --- checkpoint 24: the owner's browser routes ---------------------------------
 (["tests/test_interactive_browser_api.py"], [
   ("van_gateway/app.py",
    "        if is_interactive_browser_owner_route(path):\n            # Rev 1.5 §6.1",
    "        if False:\n            # Rev 1.5 §6.1",
    "C24 the interactive routes fall back to the Hermes-only scope"),
   ("van_gateway/browser/interactive_api.py",
    "        if session.owner_device_id != device_id:",
    "        if False:",
    "C24 any paired device can drive the owner's browser session"),
   ("van_gateway/browser/interactive_api.py",
    '    return path == INTERACTIVE_SESSION_PREFIX or path.startswith(INTERACTIVE_SESSION_PREFIX + "/")',
    "    return path.startswith(INTERACTIVE_SESSION_PREFIX)",
    "C24 a look-alike path is treated as the owner's session surface"),
   ("van_gateway/app.py",
    "    if browser_stream_grants is not None:\n        app.include_router(build_interactive_router(",
    "    if True:\n        app.include_router(build_interactive_router(",
    "C24 the routes mount with no signing key configured"),
   ("van_gateway/browser/interactive_api.py",
    '            raise HTTPException(status_code=404, detail="interactive_session_unknown")\n        return session',
    "            pass\n        return session",
    "C24 the ownership refusal is reported and then ignored"),
 ]),
 # --- checkpoint 25: the input protocol and quality adaptation --------------------
 #
 # The edge de-duplication entry is the fifth time in this programme that two guards fired
 # together and neither could be shown to matter. The isolating case is a duplicate DOWN
 # arriving after its own UP, where the epoch guard no longer applies.
 (["tests/test_browser_input_protocol.py"], [
   ("van_gateway/browser/input_protocol.py",
    "    if raw[0] != PROTOCOL_VERSION:",
    "    if False:",
    "C25 a packet from another protocol version is parsed anyway"),
   ("van_gateway/browser/input_protocol.py",
    "    if offset != len(raw):\n        raise InputProtocolError(REJECT_MALFORMED)",
    "    if False:\n        raise InputProtocolError(REJECT_MALFORMED)",
    "C25 trailing bytes are ignored, so two packets decode alike"),
   ("van_gateway/browser/input_protocol.py",
    "        if key in self._seen_edges:\n            return False",
    "        if False:\n            return False",
    "C25 the duplicated edge becomes a second tap"),
   ("van_gateway/browser/input_protocol.py",
    "        elif state.phase is PointerPhase.OPEN and packet.gesture_epoch <= state.epoch:",
    "        elif False:",
    "C25 a late DOWN reopens a gesture that has moved on"),
   ("van_gateway/browser/input_protocol.py",
    "        if packet.motion_seq <= state.last_motion_seq:",
    "        if False:",
    "C25 a reordered MOVE is applied, so the page jumps backwards"),
   ("van_gateway/browser/input_protocol.py",
    "        if state.phase is PointerPhase.OPEN and packet.gesture_epoch > state.epoch:\n            out.append(self._cancel_for(state, now_ms))",
    "        if False:\n            out.append(self._cancel_for(state, now_ms))",
    "C25 a new gesture starts without cancelling the one it replaces"),
   ("van_gateway/browser/input_protocol.py",
    "            if now_ms - state.last_seen_ms < GESTURE_TIMEOUT_MS:\n                continue",
    "            if True:\n                continue",
    "C25 a gesture can stay pressed forever after the phone vanishes"),
   ("van_gateway/browser/quality.py",
    "        return self.profile is UNMETERED_SLO and self.status is SessionQualityStatus.OK",
    "        return self.status is SessionQualityStatus.OK",
    "C25 a metered session reports high-quality certification"),
   ("van_gateway/browser/quality.py",
    "        if sample.metered and not sample.owner_allows_high_quality_on_metered:\n            return METERED_LADDER",
    "        if False:\n            return METERED_LADDER",
    "C25 metered data gets the unmetered bitrate ladder by default"),
   ("van_gateway/browser/quality.py",
    "            if self._streak >= UPGRADE_STREAK:",
    "            if True:",
    "C25 quality climbs on a single good sample"),
   ("van_gateway/browser/quality.py",
    "        if sample.rtt_ms > profile.max_rtt_ms * 2:",
    "        if False:",
    "C25 an unusable round trip is reported as an encoder problem"),
 ]),
 # --- checkpoint 26: the durable logical session ----------------------------------
 #
 # Two survived a first pass and both named a gap rather than a redundancy. The session
 # epoch is checked in two places — resume and the envelope — and only one was driven. The
 # unknown-kind check has a second refusal further down, and the difference only shows when
 # the unknown kind carries an idempotency key: refused late, it burns the key the owner's
 # real command needed.
 (["tests/test_van_hermes_session.py"], [
   ("van_gateway/session/service.py",
    "            if envelope.path_epoch != session.authoritative_path_epoch:",
    "            if False:",
    "C26 a frame from a retired path becomes a new command"),
   ("van_gateway/session/service.py",
    "        if envelope.session_epoch != session.session_epoch:\n            raise SessionError(REJECT_STALE_SESSION_EPOCH)",
    "        if False:\n            raise SessionError(REJECT_STALE_SESSION_EPOCH)",
    "C26 an invalidated session epoch keeps working"),
   ("van_gateway/session/service.py",
    "        digest = envelope.digest()\n        if envelope.payload_digest is not None and envelope.payload_digest != digest:",
    "        digest = envelope.payload_digest or envelope.digest()\n        if False:",
    "C26 the envelope vouches for its own payload"),
   ("van_gateway/session/service.py",
    '        if existing["payload_digest"] != digest:',
    "        if False:",
    "C26 a different payload under a known key is executed"),
   ("van_gateway/session/service.py",
    "        if len(routes) >= 2:",
    "        if len(usable) >= 2:",
    "C26 protocol diversity is reported as route redundancy"),
   ("van_gateway/session/service.py",
    '        usable = [p for p in paths if PathHealth(p["health"]).usable]',
    "        usable = list(paths)",
    "C26 a failed path counts towards redundancy"),
   ("van_gateway/session/router.py",
    "        if envelope.kind not in UPSTREAM_KINDS:",
    "        if False:",
    "C26 an unknown kind is routed rather than refused"),
   ("van_gateway/session/router.py",
    "        if envelope.expires_at_ms is not None and envelope.expires_at_ms <= now:",
    "        if False:",
    "C26 an expired command executes late"),
   ("van_gateway/session/router.py",
    "        if admission is CommandAdmission.ALREADY_KNOWN:",
    "        if False:",
    "C26 a resubmitted command executes a second time"),
   ("van_gateway/session/router.py",
    '        if envelope.kind in {"session.heartbeat", "session.ack"}:',
    "        if False:",
    "C26 a heartbeat occupies an idempotency key"),
 ]),
 # --- checkpoint 27: the owner device binding and signed connectivity -------------
 (["tests/test_owner_device_binding.py"], [
   ("van_gateway/auth/device_proof.py",
    "    if facts.challenge != challenge:",
    "    if False:",
    "C27 an attestation for an older challenge is accepted"),
   ("van_gateway/auth/device_proof.py",
    "    if policy.require_hardware_backed and not facts.attestation_security_level.hardware_backed:",
    "    if False:",
    "C27 a software-only key is accepted as hardware-backed"),
   ("van_gateway/auth/device_proof.py",
    "    if policy.require_verified_boot and facts.verified_boot_state is not VerifiedBootState.VERIFIED:",
    "    if False:",
    "C27 a device that failed verified boot is accepted"),
   ("van_gateway/auth/device_proof.py",
    "    if facts.package_name != policy.expected_package:",
    "    if False:",
    "C27 another app on the same phone can bind the owner slot"),
   ("van_gateway/auth/device_proof.py",
    '    if (facts.signing_cert_sha256 or "").lower() != policy.expected_signing_cert_sha256.lower():',
    "    if False:",
    "C27 a rebuilt app with a different signing key binds"),
   ("van_gateway/auth/device_proof.py",
    "    if abs(now - issued_at_ms) > PROOF_SKEW_MS:",
    "    if False:",
    "C27 an old signature stays a valid credential"),
   ("van_gateway/auth/device_proof.py",
    '        "van-device-proof-v1", method.upper(), path, device_id, str(issued_at_ms), body_sha256,',
    '        "van-device-proof-v1", method.upper(), device_id, str(issued_at_ms),',
    "C27 a proof no longer binds the route or the body"),
   ("van_gateway/connectivity/config.py",
    "    if version < minimum_version:",
    "    if False:",
    "C27 an old manifest can be replayed at a device that moved on"),
   ("van_gateway/connectivity/config.py",
    "    if kid not in trusted_keys:",
    "    if False:",
    "C27 an unknown signing key is tried rather than refused"),
   ("van_gateway/connectivity/config.py",
    "        leaked = FORBIDDEN_MANIFEST_FIELDS & set(manifest)",
    "        leaked = set()",
    "C27 a manifest may carry a pairing token"),
   ("van_gateway/connectivity/config.py",
    "        if current is not None and version <= current.manifest_version:",
    "        if False:",
    "C27 the gateway republishes an older manifest version"),
 ]),
 # --- checkpoint 28: the device proof is actually required ---------------------
 #
 # Every one of these leaves the unit tests in test_owner_device_binding.py green.
 # That is the point: the verifier was correct and nothing called it, so the only
 # tests that can see these are the ones that drive the ingress.
 (["tests/test_device_proof_enforcement.py"], [
   ("van_gateway/app.py",
    "        if requires_device_proof(request.method, request.url.path):",
    "        if False:",
    "C28 the proof is verified by nobody, as before"),
   ("van_gateway/app.py",
    "        if not signature_b64 or not issued_at_raw:",
    "        if False:",
    "C28 a missing proof header is treated as a valid proof"),
   ("van_gateway/app.py",
    "        binding = await owner_device_bindings.active()",
    "        binding = await owner_device_bindings.for_device(device_id)",
    "C28 a second paired device skips the gate by never enrolling"),
   ("van_gateway/app.py",
    "        if binding.device_id != device_id:",
    "        if False:",
    "C28 any device may present the owner's proof"),
   ("van_gateway/app.py",
    "        body = await request.body()",
    "        body = b\"\"",
    "C28 the proof covers an empty body rather than this request's"),
   # A mutation here used to delete a hand-rolled body replay and change nothing,
   # because Starlette's BaseHTTPMiddleware already caches a body read in dispatch. The
   # replay was removed rather than the mutation weakened; the one above, which empties
   # the body the proof is computed over, is what proves the digest is this request's.
   ("van_gateway/app.py",
    '        if method not in {"POST", "PUT", "PATCH", "DELETE"}:',
    "        if False:",
    "C28 a Keystore signature is demanded on every poll"),
 ]),
]

SERVICES = "services/browser_control_agent"
AGENT_TESTS = ["services"]
HOST = "services/browser_stream_host"

#: Checkpoint 29 — the Browser Control Agent. These run from the repository root rather
#: than from backend/, because the agent is not part of the Gateway: it runs on the Browser
#: Stream Host, and the whole point of §13.2 is that those are different machines with
#: different authority.
CONTROL_AGENT = [
 (f"{SERVICES}/authority.py",
  "        if operation.actuates:",
  "        if False:",
  "C29 a lease is never checked, so a preempted agent keeps typing"),
 (f"{SERVICES}/authority.py",
  "        if lease.generation != lease_generation:",
  "        if False:",
  "C29 the owner takes control back and the agent does not notice"),
 (f"{SERVICES}/authority.py",
  "        if lease.holder != caller.common_name:",
  "        if False:",
  "C29 one service may use another's lease"),
 (f"{SERVICES}/authority.py",
  "        if task.scope not in caller.scopes:",
  "        if False:",
  "C29 mTLS says who, and then nothing says what"),
 (f"{SERVICES}/authority.py",
  "        if operation not in SCOPE_ALLOWS[task.scope]:",
  "        if False:",
  "C29 an observe-only task may actuate"),
 (f"{SERVICES}/authority.py",
  "        if task.steps_remaining == 0:",
  "        if False:",
  "C29 a task that has gone wrong runs forever"),
 (f"{SERVICES}/authority.py",
  "        task.steps_used += 1",
  "        pass",
  "C29 the budget is never spent, which is the same as not having one"),
 (f"{SERVICES}/agent.py",
  "    if not (url.startswith(\"https://\") or url.startswith(\"http://\")):",
  "    if False:",
  "C29 file:/// reads the host's disk into a page the owner is watching"),
 (f"{SERVICES}/cdp.py",
  "        if not address.is_loopback:",
  "        if False:",
  "C29 the CDP client may be pointed at another host's browser"),
 (f"{SERVICES}/cdp.py",
  "            raise CdpUnavailable(\"cdp_endpoint_must_be_a_loopback_literal\") from exc",
  "            return",
  "C29 a hostname is accepted, and resolves on a machine we do not control"),
 (f"{SERVICES}/server.py",
  "    if address in {\"\", \"0.0.0.0\", \"::\", \"*\"}:",
  "    if False:",
  "C29 the only bridge to Chromium binds to the internet"),
 (f"{SERVICES}/server.py",
  "    if not parsed.is_private:",
  "    if False:",
  "C29 the control agent binds to a public address"),
 (f"{SERVICES}/server.py",
  "    context.verify_mode = ssl.CERT_REQUIRED",
  "    context.verify_mode = ssl.CERT_OPTIONAL",
  "C29 a caller with no client certificate completes the handshake"),
 # RB-017. The last step before a tap becomes a click, where a wrong answer is a
 # well-formed packet landing somewhere the owner did not touch.
 (f"{HOST}/input_router.py",
  "        if packet.authority.viewport_revision != self.viewport.revision:",
  "        if False:",
  "C29 a packet built against the previous layout is transformed rather than refused"),
 (f"{HOST}/input_router.py",
  "        if packet.authority.control_generation != self.control_generation:",
  "        if False:",
  "C29 a preempted agent's input still reaches the page"),
 (f"{HOST}/input_router.py",
  '        return [self._pointer(packet, "mouseMoved"), self._pointer(packet, "mousePressed")]',
  '        return [self._pointer(packet, "mousePressed")]',
  "C29 a press without a move, so a hover-dependent page is clicked in the wrong place"),
 (f"{HOST}/input_router.py",
  '                "buttons": 0 if event_type == "mouseReleased" else 1,',
  '                "buttons": 0,',
  "C29 a drag reports no button held, and ends halfway through"),
 (f"{HOST}/input_router.py",
  '        return [self._pointer(packet, "mouseReleased")]\n\n    def _scroll',
  '        return []\n\n    def _scroll',
  "C29 a cancel is dropped, leaving the page holding a press"),
 (f"{HOST}/input_router.py",
  '            params["text"] = packet.text',
  '            pass',
  "C29 a printable key fires an event and types nothing"),
 (f"{HOST}/input_router.py",
  '    return (detents / 120.0) * (extent * 0.2)',
  '    return float(detents)',
  "C29 a scroll is a fixed pixel count, whatever the viewport is"),
 (f"{HOST}/input_router.py",
  '        handler = _ROUTES.get(packet.kind)',
  '        handler = _ROUTES.get(packet.kind, CdpInputRouter._move)',
  "C29 an unmapped kind is silently treated as a pointer move"),
]

APP_KT = "android/app/src/main/java/com/dial/van"
ENV_KT = f"{APP_KT}/runtime/VanResourceEnvelope.kt"
EVT_KT = f"{APP_KT}/events/EventStream.kt"

#: Mutations against files outside backend/ — the workflow, the Gradle scripts — checked by
#: contract tests that run from the repository root. Kept separate rather than folded into
#: ALL because both the mutation root and pytest's working directory differ.
ROOT_LEVEL = [
 # --- checkpoint 20/21: owner surfaces and the removal assertion ----------------
 (["tests/contracts/test_owner_surfaces_are_reachable.py"], [
   ("android/app/src/main/java/com/dial/van/command/CommandCentreActivity.kt",
    "            CommandModule.MISSIONS -> MissionsModule(app, glass)\n", "",
    "C20 the work screen has no render branch"),
   ("android/app/src/main/java/com/dial/van/command/CommandModule.kt",
    '    MISSIONS("missions", "Work"),\n', "", "C20 the work screen is not navigable"),
   ("android/app/src/main/java/com/dial/van/command/modules/MissionsModule.kt",
    "                .onSuccess { snapshot = it; error = null }",
    "                .onSuccess { error = null }",
    "C20 the work screen never binds the repository result"),
   ("android/app/src/main/java/com/dial/van/command/modules/NotificationPolicyModule.kt",
    "                                    store.setPolicy(entry.key, option)",
    "                                    reload()", "C20 setting an app policy does nothing"),
   ("android/app/src/main/java/com/dial/van/command/modules/MissionsModule.kt",
    "    var expanded by rememberSaveable { mutableStateOf<String?>(null) }",
    "    var expanded by remember { mutableStateOf<String?>(null) }",
    "C20 the open mission is lost on rotation"),
 ]),
 # --- checkpoint 22: what signed the APK the owner installs --------------------
 (["tests/contracts/test_debug_signing_identity.py"], [
   ("tools/ci/restore_debug_keystore.sh",
    'if ! keytool -list -keystore "$tmp" -storepass android -alias androiddebugkey >/dev/null 2>&1; then',
    'if false; then',
    "C22 a keystore Android cannot open is accepted and the build signs with the runner's"),
   # The first attempt here edited the branch's opening line and survived: the sentence the
   # test pins is two lines further down, so the mutation changed nothing the test was
   # about. A mutation that misses is not evidence either way.
   ("tools/ci/restore_debug_keystore.sh",
    '  echo "debug-keystore: machine, so its APK cannot upgrade one from any other run, and an"',
    '  echo "debug-keystore: machine."',
    "C22 the no-key run stops naming the consequence"),
   ("tools/ci/restore_debug_keystore.sh",
    'echo "debug-keystore: set the VAN_DEBUG_KEYSTORE_BASE64 secret to fix that."\n  exit 0',
    'echo "debug-keystore: set the VAN_DEBUG_KEYSTORE_BASE64 secret to fix that."',
    "C22 a run with no key falls through into the restore path"),
   ("tools/ci/record_apk_signing_identity.sh",
    "if ! grep -q 'SHA-256 digest' \"$out\"; then",
    "if false; then",
    "C22 an apksigner that prints no certificate publishes an empty identity"),
   ("tools/ci/record_apk_signing_identity.sh",
    'if [ -z "$apk" ]; then',
    'if false; then',
    "C22 a build that produced no APK still reports a signature"),
   (".github/workflows/van-ci.yml",
    "            android/app/build/outputs/apk/debug/signing-identity.txt\n", "",
    "C22 the identity stays on the runner"),
 ]),
 (["tests/contracts/test_maturity_gate.py"], [
   ("backend/van_gateway/epistemics/models.py", "class SemanticClass(str, Enum):",
    "class Claim:\n    pass\n\n\nclass SemanticClass(str, Enum):",
    "C21 a deleted class comes back and the removal claim stands"),
   ("tools/ci/maturity_gate.py", "(?:class|object)", "(?:NOTACLASS|NOTANOBJECT)",
    "C21 the gate stops recognising a deleted class"),
   ("tools/ci/maturity_gate.py", "(?:suspend\\s+)?fun\\s+", "(?:suspend\\s+)?NOTAFUN\\s+",
    "C21 the gate stops recognising a deleted Kotlin function"),
   ("tools/ci/maturity_gate.py", "(?:async\\s+)?def\\s+", "(?:async\\s+)?NOTADEF\\s+",
    "C21 the gate stops recognising a deleted Python function"),
 ]),
 # --- checkpoint 19: Google routes and the premise ingress ---------------------
 (["tests/test_google_capabilities_have_routes.py", "tests/test_control_scopes.py"], [
   ("van_gateway/app.py", '    "/v1/google/drive/search",\n    "/v1/google/contacts/resolve",\n', "",
    "C19 two new routes fall outside the scope set"),
   ("van_gateway/app.py",
    "            return await google.calendar_reschedule(event_id, new_start_unix, approved=approved)",
    "            return await google.calendar_reschedule(event_id, new_start_unix, approved=True)",
    "C19 rescheduling approves itself"),
   ([("van_gateway/app.py", '    "/v1/google/tasks",\n', ""),
     ("van_gateway/app.py",
      "        require_internal_control(x_van_internal_token, ControlScope.GOOGLE)\n        try:\n            return {\"tasks\": await google.tasks_list()}",
      "        try:\n            return {\"tasks\": await google.tasks_list()}")],
    "C19 the owner's tasks reachable with a device token (both guards removed)"),
 ]),
 (["tests/test_irreversible_work_waits_on_assumptions.py"], [
   ("van_gateway/runtime_api.py", '        @router.post("/reasoning/premises")\n',
    '        @router.post("/reasoning/premises-disabled")\n',
    "C19 the premise ingress moves and nothing records"),
   ("van_gateway/reasoning/kernel.py",
    "            and semantic_class in (SemanticClass.FACT_VERIFIED, SemanticClass.FACT_UNVERIFIED)",
    "            and True", "C19 agreeing with a preference counts as unsupported agreement"),
   ("van_gateway/reasoning/kernel.py", "            not corrected\n", "            True\n",
    "C19 a correction is counted as agreement"),
   ("van_gateway/reasoning/kernel.py", "            and not refs\n", "            and True\n",
    "C19 citing evidence no longer makes agreement well-founded"),
 ]),
 # --- checkpoint 18: the ledger reconciler -------------------------------------
 # Six mutations, and getting three of them to fail took three attempts each. The tool's
 # two test-exclusion rules overlap on every file in this repository, so any fixture driven
 # through the search satisfies both and neither can be falsified alone.
 (["tests/contracts/test_ledger_reconcile.py"], [
   ("tools/ci/ledger_reconcile.py", '    if "/test" in path:\n        return False\n', "",
    "C18 a test-path reference counts as a production consumer"),
   ("tools/ci/ledger_reconcile.py",
    '    if Path(path).name.startswith("test_"):\n        return False\n', "",
    "C18 a test_-named file counts as a production consumer"),
   ("tools/ci/ledger_reconcile.py", "    return path not in set(excludes or [])", "    return True",
    "C18 a reference from dead code counts as integration"),
   ("tools/ci/ledger_reconcile.py", "    if contradicted:", "    if False:",
    "C18 stop failing when the ledger understates"),
   ("tools/ci/ledger_reconcile.py",
    "            unverifiable.append(f\"{name} ({c.get('maturity_class')})\")",
    "            confirmed.append(name)", "C18 an entry with no symbols counts as verified"),
   ("tools/ci/ledger_reconcile.py",
    '        if c.get("maturity_class") not in CLAIMS_UNREACHED:', "        if False:",
    "C18 check classes that assert nothing about reachability"),
 ]),
 # --- checkpoint 15: the Kotlin reachability scanner ---------------------------
 # A scanner is only as good as what it refuses to count. The first four here are the
 # manifest parse and the three ways a symbol can appear without being a call site; a
 # sweep that counts a KDoc mention makes every well-documented dead class look alive,
 # which is the confusion this whole programme exists to correct.
 (["tests/contracts/test_kotlin_reachability.py"], [
   ("tools/audit/kotlin_reachability.py",
    'r"<(?:activity|activity-alias|service|receiver|provider|application)\\b[^>]*?"\n    r\'android:name="\\.?([A-Za-z0-9_.]+)"\'',
    'r\'android:name="\\.?([A-Za-z0-9_.]+)"\'',
    "C15 the manifest sweep treats permissions as components again"),
   ("tools/audit/kotlin_reachability.py", '    text = re.sub(r"//[^\\n]*", " ", text)', "    pass",
    "C15 a symbol named in a line comment counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    '    text = re.sub(r"/\\*.*?\\*/", " ", text, flags=re.DOTALL)', "    pass",
    "C15 a symbol named in a KDoc counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    """    text = re.sub(r'"(?:[^"\\\\\\n]|\\\\.)*"', ' "" ', text)""", "    pass",
    "C15 a symbol named in a string counts as a call site"),
   ("tools/audit/kotlin_reachability.py",
    '    text = re.sub(r"//[^\\n]*", " ", text)', '    text = re.sub(r".*", " ", text)',
    "C15 strip everything, so all code looks dead"),
   ("tools/audit/kotlin_reachability.py",
    'r"(?:(?:enum|annotation|companion)\\s+)?"', '""',
    "C15 miss enum and annotation declarations"),
   ("tools/audit/kotlin_reachability.py",
    "        if not reached_by and not reached_by_tests:", "        if False:",
    "C15 stop reporting files nothing references"),
   ("tools/audit/kotlin_reachability.py",
    "        elif not reached_by and reached_by_tests:", "        elif False:",
    "C15 stop reporting test-only symbols"),
 ]),
 # --- checkpoint 14: the runtime envelope's wiring ----------------------------
 # The envelope's arithmetic is mutated under Gradle (see KOTLIN below). These are the
 # Python half: whether anything in the shipping app actually asks it. A fully tested
 # envelope that no production path reaches is the audit's most common defect shape.
 (["tests/contracts/test_the_runtime_envelope_governs.py"], [
   (f"{APP_KT}/visual/VanCanvasFallback.kt", "VanResourceEnvelope.effectBudget(",
    "VanEffectPolicy.resolve(", "C14 the embodiment resolves its own budget again"),
   (f"{APP_KT}/command/modules/WorkModules.kt",
    "stream, truncated, DeviceRuntimeReadings.pressure(context),", "stream, truncated,",
    "C14 the poll loop takes the default pressure"),
   (f"{APP_KT}/telemetry/DeviceTelemetryReporter.kt",
    "delay((FLUSH_INTERVAL_MS * allowance.cadenceScale).toLong())", "delay(FLUSH_INTERVAL_MS)",
    "C14 the flush interval ignores the allowance"),
   (f"{APP_KT}/command/modules/WorkModules.kt", ") ?: break", ") ?: 0L",
    "C14 a stop is coerced back into a delay"),
   (f"{APP_KT}/runtime/VanResourceEnvelope.kt",
    "        VanSubsystem.WAKE_WORD,\n        VanSubsystem.OWNER_COMMAND,\n        VanSubsystem.DEGRADED_REPORTING,\n",
    "", "C14 empty the never-shed set"),
   (f"{APP_KT}/runtime/VanResourceEnvelope.kt", "const val UNKNOWN = -1", "const val UNKNOWN = 0",
    "C14 an unreadable battery reads as flat"),
   (f"{APP_KT}/runtime/DeviceRuntimeReadings.kt", "context.filesDir.usableSpace", "0L",
    "C14 stop reading free storage"),
 ]),
 # --- checkpoint 12: the APK leaves CI ----------------------------------------
 (["tests/contracts/test_the_apk_leaves_ci.py",
   "tests/contracts/test_ci_workflow_is_what_it_claims.py"], [
   (".github/workflows/van-ci.yml",
    """      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: van-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
""", "", "C12 drop the APK upload entirely"),
   (".github/workflows/van-ci.yml", "if-no-files-found: error\n      - name: Shared visual",
    "if-no-files-found: warn\n      - name: Shared visual",
    "C12 publish an empty artefact instead of failing"),
   (".github/workflows/van-ci.yml", "path: android/app/build/outputs/apk/debug/*.apk",
    "path: android/app/build/outputs/apk/release/*.apk",
    "C12 point the upload at a variant the build never assembles"),
   (".github/workflows/van-ci.yml",
    "./gradlew :app:testDebugUnitTest :app:assembleDebug :app:lintDebug",
    "./gradlew :app:testDebugUnitTest :app:lintDebug",
    "C12 stop assembling the APK but keep uploading it"),
   ("android/settings.gradle.kts", 'include(":app")', 'include(":application")',
    "C12 rename the module out from under the artifact path"),
   ("android/app/build.gradle.kts", 'id("com.android.application")',
    'id("com.android.library")', "C12 a module that emits an AAR, not an APK"),
 ]),
]

#: Checkpoint 14, Kotlin half. Run by Gradle in android/verification rather than by pytest,
#: because that harness is the only thing in this repository that can execute Kotlin at all.
KOTLIN = [
 (ENV_KT, "status >= THERMAL_CRITICAL -> RuntimePressure.SURVIVAL",
  "status >= THERMAL_CRITICAL -> RuntimePressure.NOMINAL",
  "C14 thermal critical reads as fine"),
 ([(ENV_KT, '            add("thermal" to thermalPressure(reading.thermalStatus))',
    '            if (!reading.charging) add("thermal" to thermalPressure(reading.thermalStatus))')],
  "C14 being on a charger excuses the heat"),
 (ENV_KT, "        val pressure = contributions.maxOf { it.second }",
  "        val pressure = contributions.last().second",
  "C14 pressure is the last input rather than the worst"),
 # Compound: the never-shed promise is held by a guard clause and by the table it guards,
 # so neither edit alone changes behaviour. A single-edit mutation surviving for that reason
 # would say nothing about whether the promise is tested.
 ([(ENV_KT, "        if (subsystem in NEVER_SHED) return Allowance.FULL",
    "        if (false) return Allowance.FULL"),
   (ENV_KT, """            VanSubsystem.WAKE_WORD,
            VanSubsystem.OWNER_COMMAND,
            VanSubsystem.DEGRADED_REPORTING,
            -> Allowance.FULL""",
    """            VanSubsystem.WAKE_WORD,
            VanSubsystem.OWNER_COMMAND,
            VanSubsystem.DEGRADED_REPORTING,
            -> if (pressure.atLeast(RuntimePressure.CRITICAL)) Allowance.STOPPED else Allowance.FULL""")],
  "C14 the wake word is shed under pressure"),
 (ENV_KT, "        VanEffectBudget.REDUCED_MOTION -> 1", "        VanEffectBudget.REDUCED_MOTION -> 3",
  "C14 reduced motion ranked as rich, so pressure clamps it into a moving budget"),
 (ENV_KT, "        return if (rank(ladder) <= rank(ceiling)) ladder else ceiling",
  "        return if (rank(ladder) >= rank(ceiling)) ladder else ceiling",
  "C14 the envelope raises the embodiment's budget"),
 (ENV_KT,
  "                pressure.atLeast(RuntimePressure.CRITICAL) -> Allowance.STOPPED\n                pressure.atLeast(RuntimePressure.CONSTRAINED) -> Allowance(true, 4.0)",
  "                pressure.atLeast(RuntimePressure.CRITICAL) -> Allowance(false, 4.0)\n                pressure.atLeast(RuntimePressure.CONSTRAINED) -> Allowance(true, 4.0)",
  "C14 a stopped subsystem keeps a cadence"),
 (EVT_KT, "    const val CATCH_UP_POLL_MS = 0L", "    const val CATCH_UP_POLL_MS = 500L",
  "C14 catch-up stops being immediate, so pressure now stretches it"),
 (EVT_KT, "        return (base * allowance.cadenceScale).toLong().coerceAtMost(MAX_BACKOFF_MS)",
  "        return (base * allowance.cadenceScale).toLong()",
  "C14 a stretched backoff exceeds the ceiling"),
 (EVT_KT, "        if (!allowance.running) return null", "        if (false) return null",
  "C14 SURVIVAL keeps polling"),
]

ROOT = pathlib.Path(__file__).resolve().parents[2]


def groups(selector: str | None = None):
    """The groups to run. `selector` matches the checkpoint tag on a group's mutations.

    Selecting matters more than it looks: the full suite is several hundred subprocess
    pytest runs, and a run that is interrupted leaves the tree mutated. Being able to say
    "just the checkpoint I am working on" is the difference between a two-minute check and
    a thirty-minute one that gets killed.
    """
    for tests, mutations in ALL:
        if selector and not any(selector in mutation[-1] for mutation in mutations):
            continue
        yield tests, mutations, {}
    for tests, mutations in ROOT_LEVEL:
        if selector and not any(selector in mutation[-1] for mutation in mutations):
            continue
        yield tests, mutations, {"root": ROOT, "cwd": ROOT}
    for tests, mutations in ((AGENT_TESTS, CONTROL_AGENT),):
        if selector and not any(selector in mutation[-1] for mutation in mutations):
            continue
        yield tests, mutations, {"root": ROOT, "cwd": ROOT}


def main(selector: str | None = None) -> int:
    survivors = []
    for tests, mutations, options in groups(selector):
        print(f"\n### {tests}", flush=True)
        survivors += run(mutations, tests, **options)

    if not selector or any(selector in mutation[-1] for mutation in KOTLIN):
        print("\n### android/verification (Gradle)", flush=True)
        survivors += run(
            KOTLIN, [], root=ROOT, cwd=ROOT / "android" / "verification",
            command=["gradle", "test", "--console=plain", "--offline", "--rerun-tasks"],
        )
    print("\n================ SURVIVORS ================")
    print("\n".join(survivors) or "none")
    return 1 if survivors else 0


if __name__ == "__main__":
    # Guarded, so this file can be imported to select a subset without running all of it.
    # It was not: `import mutation_suite` executed the entire suite as a side effect, which
    # is how a run meant to check seven mutations spent twenty minutes on the other three
    # hundred and was then killed, leaving a source file mutated in the tree.
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else None))
