"""Concrete owner journeys. Fixtures are requirements, never invented API routes."""

# feature: (prepared isolated data, action, deliberately failing fixture, readback)
JOURNEYS = {
    "OF-HOME-001": ("Mission, attention, reminder and project with distinct IDs", "Open every highlighted record and refresh", "One overview source unavailable while others remain healthy", "Highlighted IDs and timestamps match their source records"),
    "OF-COMMAND-001": ("Harmless command with deterministic service postcondition", "Submit once; inspect pending, verifying and terminal mission", "Hermes accepts but its reply is lost", "One command identity, one Hermes run, one independently observed effect"),
    "OF-MISSION-001": ("Completed mission with durable evidence and a second distinct mission", "Open named mission, activity and evidence; recreate activity", "Unknown mission and unavailable evidence", "Same selected mission ID and inspectable verification receipt"),
    "OF-MISSION-002": ("Disposable running mission and a separate mission for messaging", "Record direction and cancel through displayed controls", "Terminal transition conflict or lost mutation response", "Direction is recorded on exact mission; cancellation does not imply remote work stopped"),
    "OF-ATTENTION-001": ("Two disposable attention items with different urgency", "Open, acknowledge and snooze selected items", "Ack or snooze persistence rejected", "Same item readback and actual snooze time; failed item remains actionable"),
    "OF-DECISION-001": ("Exact expiring decision bound to a disposable mission", "Inspect evidence, choose and inspect associated attention", "Expired decision or stale revision", "Exact decision lifecycle; decision resolution does not confer cryptographic action approval"),
    "OF-APPROVAL-001": ("Disposable elevated command with sealed intent and unexpired challenge", "Inspect scope and approve exact occurrence using owner biometric", "Cancel biometric; change intent; expire or replay challenge", "Only exact approved occurrence can execute; independent postcondition precedes success"),
    "OF-REMINDER-001": ("Unique reminder label and explicit Africa/Harare due time", "Create, inspect due time, resolve and cancel separate reminders", "Invalid date and lost create response", "Original reminder identity, correct due instant and no duplicate record"),
    "OF-MEMORY-001": ("Disposable scoped owner fact unrelated to real personal memory", "State, supersede, inspect and withdraw fact", "Storage/auth refusal while a draft is present", "Exact scope/provenance and supersession chain; withdrawn fact is ineffective"),
    "OF-MEMORY-002": ("Separate disposable owner database and captured per-store counts", "Inspect export; approve exact store erasure; inspect effect receipt", "Cancelled biometric, unknown store or approval expiry", "Verified counts and dependency closure; deliberately retained audit/authority records remain"),
    "OF-MEMORY-003": ("Two conflicting disposable facts and revision history", "Inspect both conflict sides and issue explicit owner correction", "History unavailable or malformed conflict projection", "Conflict sides and correction provenance retained; outage differs from empty history"),
    "OF-LEARNING-001": ("Disposable assertions, known project/global vocabulary and domain collaboration instruction", "Confirm/correct/reject assertions; define/edit a term and explicit collaboration preference", "Revoked owner, stale session epoch, unknown project or invalid declaration", "Exact committed declaration and OWNER_AUTHORED provenance; no inferred trait, execution grant or future-model-compliance claim"),
    "OF-LEARNING-002": ("One reversible and one irreversible disposable adaptation", "Inspect, confirm and revert reversible adaptation", "Attempt rollback of irreversible adaptation", "Readback of actual adaptation state; ADAPTATION_NOT_REVERSIBLE remains a refusal"),
    "OF-LEARNING-003": ("Contradictory goals and measured/unmeasured evaluation dimensions", "Inspect goals, decisions, strategies, reality, radar and evaluation", "Evidence source unavailable", "Untested, inconclusive and measured results remain distinct; no fabricated accuracy"),
    "OF-PROJECT-001": ("Two registered acceptance projects with distinct work IDs", "Open each project and related record; issue harmless project-bound command", "Unknown project or missing truth", "Exact project ID follows navigation and command context"),
    "OF-PROJECT-002": ("Disposable project with rejected strategy and rationale history", "Record owner-authored rationale and read exact project back", "Duplicate rejected rationale or lost submission reply", "Same-project rationale/evidence; current Project Truth unchanged"),
    "OF-AUTHORITY-001": ("Disposable standing root grant and actual admitted action namespace", "Inspect/revoke a grant; choose a supported S0..S4 ceiling and biometrically approve its exact sealed change", "Already revoked grant, unknown domain, expired/changed approval or superseded lost reply", "Exact operation-specific stored owner ceiling and effective cap; revocation prevents new work and a ceiling creates no action authority"),
    "OF-GOOGLE-001": ("Separate acceptance Google account with scoped owner OAuth", "Inspect each account plane; disconnect and privately restore owner OAuth", "Expired owner OAuth while provider/service plane remains healthy", "Only selected OAuth plane changes; owner privately completes consent"),
    "OF-GOOGLE-002": ("Acceptance mailbox, calendar, Drive and contacts; controlled recipient", "Search/read, draft, then freshly approve one exact write", "Scope denied, expired approval or provider reply lost", "Provider readback of exact message/event/task; draft or accepted is not sent"),
    "OF-KNOWLEDGE-001": ("Acceptance corpus and deterministic query with known citations", "Query through Work; inspect research, providers and citations", "One provider unavailable or citation verification missing", "Source-backed citations and operation state; configuration differs from readiness"),
    "OF-AUTOMATION-001": ("Disposable standing intent and harmless bounded automation target", "Inspect run; invoke advertised command; disable exact standing intent", "Expired authority or ambiguous automation outcome", "Independent target effect and exact intent disable/revocation; no new action after withdrawal"),
    "OF-BROWSER-001": ("Acceptance browser task and controlled escalation", "Inspect task, escalation, policy and owner-visible outcome", "Task finishes without independent task-goal verification", "Transport/task completion remains distinct from verified owner goal"),
    "OF-BROWSER-002": ("Controlled test website with tabs, gestures and visible generation marker", "Navigate, exercise controls, acknowledge viewport, pause and close", "Control POST fails or remote close outcome is unknown", "Matching viewport/lease; failed control visible; local disconnect does not prove remote close"),
    "OF-BROWSER-003": ("Acceptance page with fresh owner lease and matching generation", "Take control, delegate bounded work and ask about visible page", "Stale lease/generation or denied takeover", "Current owner control only after authoritative matching lease; no optimistic takeover"),
    "OF-BROWSER-004": ("Owned-session controlled download, phone SAF document, current chooser and harmless clipboard samples", "Review/remove records; explicitly save verified bytes to phone, upload a chosen document, copy selection and paste phone text", "Wrong session/target/epoch/hash, expired grant, canceled SAF chooser or ambiguous effect reply", "Metadata deletion has its own DELETED readback. Save/upload/copy/paste require exact artifact bytes/hash/length and independently observed current target effect; record removal alone proves no transfer"),
    "OF-VOICE-001": ("Owner-private microphone session with harmless exact spoken command", "Wake, listen, finish/cancel, interrupt and receive spoken result", "Permission refusal, late final recognition or interrupted transport", "Cancelled turn cannot submit late speech; POST/SSE preserves original envelope identity"),
    "OF-VOICE-002": ("Owner-private real microphone enrollment and disposable explicit speech correction; no invented voice profile", "Review dedicated biometric consent, capture three local clips, read encrypted profile readiness and separately erase the exact profile", "Missing microphone/model/current binding, changed local key/revision, expired or replayed consent, clipped/inconsistent signal or corrupt encrypted profile", "Exact private local profile revision/presence and current model/binding readback; similarity is evidence only and erasure can use genuine local keys offline"),
    "OF-OVERLAY-001": ("S24 overlay permission and harmless foreground test app", "Tap, double tap, long press, drag/dock, dismiss and restore board", "Overlay permission revoked or foreground context unavailable", "Gestures preserve command state and selected context; no accidental dispatch"),
    "OF-NOTIFICATION-001": ("Controlled notification from a test app and private deny-policy sample", "Review observed app, set policy/quiet hours and inspect attention", "Listener permission revoked or test app denied", "Allowed attention captured; denied notification content absent from gateway/outbox/logs"),
    "OF-SHARE-001": ("Test text/link/file shared from a controlled Android app", "Share to VAN; inspect context; send separate explicit instruction", "Unsupported MIME or untrusted shared instruction", "Shared content remains data; no action before independent owner instruction"),
    "OF-PROVISION-001": ("Exact owner-signed arm64 APK and short-lived signed installer envelope", "Installer provisions automatically; grant OS permissions; inspect readiness", "Wrong signature/device, spent/expired ticket, attestation or CA refusal", "Hardware key, verified chain, paired device and certified session correlate; no in-app URLs/tokens"),
    "OF-SETTINGS-001": ("Admitted owner device with known current permissions", "Inspect readiness, change local preference and use supported restore", "Revoked permission or expired certificate", "Actual producer-backed signals; restoration does not erase pending identities"),
    "OF-DIAGNOSTICS-001": ("Failed harmless mission with known correlation IDs", "Open diagnostics and copy redacted receipt", "Unavailable trace projection", "Original error/correlation retained; no credentials or private host paths disclosed"),
    "OF-TRADING-001": ("Demo account and isolated price/risk fixtures", "Inspect overview, portfolio, exposure and selected detail", "Stale price, broker outage or disabled sender", "Authoritative freshness and risk gates; no stale metric confers authority"),
    "OF-TRADING-002": ("Demo positions, bars, history and opportunity evidence", "Open exact position; pan/zoom/crosshair; inspect history and intelligence", "Unknown trade, no bars or unverifiable outcome", "Exact trade identity; data/evidence-backed outcomes rather than P&L celebration"),
    "OF-TRADING-003": ("Separate demo broker account and exact account challenge", "Privately complete broker OAuth; approve only advertised demo account action", "Expired challenge, biometric refusal or failed OAuth callback", "Only intended demo account changes; no credential disclosure or real orders"),
    "OF-TRADING-004": ("Demo-only strategy, target and current certificate", "Approve exact certificate and inspect authoritative promotion readback", "Changed certificate/target, stale challenge or failed readback", "Exact promoted capsule/certificate; success waits for authoritative readback"),
    "OF-TRADING-005": ("Isolated demo sender/risk authority, actual disposable ticket and signed ticket-confirm authority", "Inspect tickets; record exact broker fill with fresh biometric approval; request supported protective halt", "Changed ticket/amount, missing ticket authority, stale biometric challenge or unavailable sender", "Independent exact chained-ledger broker receipt and current owner-halt readback; confirmation never submits an order"),
    "OF-DEV-001": ("Disposable admitted development project with advertised controls", "Open hub, plan, tasks, graph, agents, reviews and supporting records", "Revision conflict, disabled upstream or unsupported action", "Exact current upstream IDs/revisions; no simulated progress or self-authorized truth write"),
    "OF-DEV-002": ("Disposable workspace, redacted logs, diff and immutable evidence", "Open workspace and related evidence", "Gone workspace, unavailable upstream or redacted log", "Exact workspace/source revision; log tail does not replace verification"),
    "OF-ARTEMIS-001": ("Admitted device and governed owner console session", "Open device-proved embedded console", "Expired launch, missing proof or disabled service", "Governed console only; no raw upstream MCP/control credentials"),
    "OF-EMBODIMENT-001": ("Actual Rive asset plus independently controlled assistant states", "Observe listening/speaking/pending/verified result and reduced motion", "Missing renderer, unverified outcome or degraded dependency", "Only verified success confirms; accessible state and independent degradation remain visible"),
}

STATE_FIXTURES = {
    "happy": "Prepare the concrete isolated journey above and exercise every advertised action.",
    "loading": "Delay only this journey's source using an admitted acceptance fixture; observe before completion.",
    "error": "Use this journey's specific failure fixture; retain independent healthy sources.",
    "degraded": "Disable only the affected acceptance dependency; keep gateway and unrelated planes healthy.",
    "offline": "Disconnect phone networking temporarily through Artemis; leave wireless ADB recovery route available.",
    "stale": "Supply old authoritative timestamps through an admitted acceptance fixture, without changing phone time.",
    "access": "Refuse the relevant OS permission/biometric or expire only an acceptance grant; owner handles private dialogs.",
    "empty": "Use an isolated empty data scope with a successful source response, then distinguish a failed response.",
    "cancelled": "Cancel the disposable occurrence or expire its exact challenge; inspect terminal controls and no new effect.",
    "recovery": "Interrupt then restore this journey using an admitted fixture; recreate app and reconcile original record/draft.",
}

# Metadata/read success cannot qualify a byte effect or another advertised action.
FUNCTION_OUTCOMES = {
    "OF-BROWSER-004:review-downloads": ["VERIFIED_READ"],
    "OF-BROWSER-004:remove-download-record": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:save-to-phone": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:upload-from-phone": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:explicit-clipboard": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:open-in-van": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:native-file-operation": ["VERIFIED_READ"],
    "OF-BROWSER-004:external-file-contract": ["VERIFIED_READ"],
    "OF-BROWSER-004:provider-draft": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:provider-admission": ["VERIFIED_SUCCESS"],
    "OF-BROWSER-004:provider-observation": ["VERIFIED_READ"],
    "OF-VOICE-002:local-owner-enrollment": ["VERIFIED_SUCCESS"],
    "OF-VOICE-002:local-profile-readback": ["VERIFIED_READ"],
    "OF-VOICE-002:local-profile-erasure": ["VERIFIED_SUCCESS"],
}

LOCAL_SPEAKER_FUNCTIONS = {
    "OF-VOICE-002:local-owner-enrollment": "ENROLL",
    "OF-VOICE-002:local-profile-readback": "READ",
    "OF-VOICE-002:local-profile-erasure": "REMOVE",
}

# Normalized evidence labels; these are not invented wire operations/endpoints.
BYTE_EFFECT_FUNCTIONS = {
    "OF-BROWSER-004:save-to-phone": ["DOWNLOAD"],
    "OF-BROWSER-004:upload-from-phone": ["UPLOAD"],
    "OF-BROWSER-004:explicit-clipboard": ["CLIPBOARD_COPY", "CLIPBOARD_PASTE"],
    "OF-BROWSER-004:open-in-van": ["DOWNLOAD"],
    "OF-BROWSER-004:provider-admission": ["PROVIDER_WRITE"],
}

# Separate transport/lifecycle cases prevent a happy UI walk from qualifying recovery.
RECOVERY_JOURNEYS = [
    ("CC-PAIR-REPLY-LOST", "OF-PROVISION-001", "Lose the pair reply after exact ticket consumption; restore app",
     "Recover the same hash-bound attempt/key; do not mint a second ticket/device or drop pending signed payload",
     "Isolated one-use pairing attempt; admitted transport-response loss fixture"),
    ("CC-ATTEST-REPLY-LOST", "OF-PROVISION-001", "Lose successful attestation reply; restart and reconcile",
     "Recover exact active verified binding with fresh proof; distinguish unconsumed bootstrap from consumed mismatch",
     "Disposable attested binding and admitted response-loss fixture"),
    ("CC-CERTIFICATE-RENEW", "OF-PROVISION-001", "Renew the acceptance device certificate and reconnect",
     "Current certified session uses new valid serial; no exported hardware key or in-app credential entry",
     "Short-lived acceptance certificate and admitted renewal recipe"),
    ("CC-REVOKED-DEVICE", "OF-PROVISION-001", "Revoke disposable acceptance binding while a session is active",
     "Session/mutations are refused; UI exposes safe restoration and makes no new owner effect",
     "Disposable binding; no revocation of the owner's normal production phone identity"),
    ("CC-WS-POST-SSE", "OF-VOICE-001", "Make WebSocket unavailable while authenticated POST/SSE remains healthy",
     "Same envelope/session identity reaches real fallback; acknowledgment and spoken-result boundaries remain truthful",
     "Admitted WebSocket-only acceptance fault; independent POST/SSE readiness"),
    ("CC-PROCESS-DEATH-OUTBOX", "OF-COMMAND-001", "Kill process after dispatch before acknowledgement; relaunch",
     "Persistent original outbox identity reconciles one Hermes run and one service effect; no duplicate command",
     "Harmless command and admitted process-death/response-loss boundary"),
    ("CC-PHONE-REBOOT", "OF-COMMAND-001", "Reboot handset with harmless pending command and restore governed ADB",
     "Re-admit current wireless endpoint; original hardware identity/outbox/session persist and no duplicate effect occurs",
     "Independent governed wireless recovery route and harmless acceptance pending command"),
    ("CC-WIFI-MOBILE", "OF-COMMAND-001", "Switch Wi-Fi/mobile networking during a harmless owner turn",
     "Reconnect to approved pinned ingress; original identity and draft retained; missing ADB observation is blocked",
     "Governed device recovery connectivity separate from the phone data-plane transition"),
    ("CC-PIN-MISMATCH", "OF-PROVISION-001", "Present mismatched acceptance server certificate/manifest signature",
     "TLS/signature rejected before credential-bearing enrollment; no trust widening or proxy-CA acceptance",
     "Dedicated isolated ingress with deliberately invalid certificate/signature, never production ingress"),
    ("CC-HERMES-RESTART", "OF-COMMAND-001", "Restart isolated Hermes after acceptance but before callback",
     "Durable run binding/callback reconciles original command; unknown stays unknown until independent observation",
     "Separately admitted acceptance Hermes realm; no production Hermes restart"),
    ("CC-PROVIDER-UNKNOWN", "OF-GOOGLE-002", "Lose provider reply after acceptance of one controlled test write",
     "No blind replay or verified-success claim; inspect exact provider record before deciding the original outcome",
     "Acceptance provider account/recipient and admitted reply-loss fixture"),
    ("CC-LOG-PRIVACY", "OF-DIAGNOSTICS-001", "Capture diagnostic/export evidence after private dialogs and denied notification",
     "Secrets, pairing codes, protected notification content and credentials are absent from retained artifacts",
     "Synthetic secret markers in isolated test dialogs; private owner inputs never supplied to objectives"),
]
